Financial-Times/x-dash

.travis.yml, packages/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap, packages/x-teaser/rollup.config.js, packages/x-teaser/src/CustomSlot.jsx, packages/x-teaser/src/Image.jsx, packages/x-teaser/src/Link.jsx, packages/x-teaser/src/RelatedLinks.jsx, packages/x-teaser/src/Title.jsx
=> make link optional

athloi.js, lerna.json, makefile, package.json, packages/x-docs/package.json, packages/x-docs/static/storybook, packages/x-teaser/package.json, packages/x-workbench/package.json, readme.md, secret-squirrel.js
=> nicer non-maintainer dev experience

.travis.yml
=> fix travis deploy path

athloi.js, components/x-teaser/package.json, components/x-teaser/rollup.config.js, package.json, packages/x-rollup/index.js, packages/x-rollup/package.json, packages/x-rollup/rollup.template.js
=> Common rollup config for components

.travis.yml, package.json
=> is that even a thing?

tools/x-docs/src/docs/guides/components/setup.md
this is a previously undocumented requirement that caused @fenglish some trouble
=> document adding a component to storybook

components/x-interaction/readme.md, components/x-teaser/readme.md, packages/x-handlebars/readme.md
=> x-engine is no longer a peer dependency

tools/x-docs/src/docs/guides/apps/local.md
tried it with the App and it works seamlessly 😚👌
=> guide for local npm install

components/x-teaser/Props.d.ts, components/x-teaser/readme.md, components/x-teaser/src/Container.jsx, components/x-teaser/stories/knobs.js
Fixes #136 
These properties are no longer used
=> Remove obsolete syndication props

makefile, tools/x-docs/src/docs/guides/components/setup.md
Updated docs accordingly.
Fixes #167
=> Added new update-snapshots command to makefile

.circleci/config.yml
=> Deploy docs to github pages on merge to master

components/x-gift-article/readme.md, components/x-gift-article/src/GiftArticle.jsx, components/x-gift-article/src/lib/api.js, components/x-gift-article/src/lib/props-composer.js
Best to ignore whitespace on the diff: https://github.com/Financial-Times/x-dash/pull/197/files?w=1
=> x-gift-article fetch enhancement

components/x-eventpromo/bower.json
=> use es5 package for bower

components/x-teaser/Props.d.ts
Add 'audio' to ContentType
https://github.com/Financial-Times/next-article/blob/38c5c2c54f313ea128ff0aadf4eb76c85ed610ac/server/model/audio.js#L30
=> Add audio to content type

__tests__/__snapshots__/snapshots.test.js.snap, components/x-teaser/stories/index.js, components/x-teaser/stories/podcast.js
Set up a storybook data file for podcasts
=> Set up podcast story for teaser component

tools/x-docs/src/components/story-viewer/index.jsx, tools/x-docs/static/main.css
Fix a layout issue in the documentation https://financial-times.github.io/x-dash/components/x-teaser
WAS
NOW
=> Fix layout issue now we have 1 extra item

.eslintignore, release-guidelines.md
https://financialtimes.slack.com/archives/C041V9QA7/p1548067516399400)
=> Document the implications of prerelease versions and Renovate

components/x-topic-search/__tests__/x-topic-search.test.jsx, components/x-topic-search/src/TopicSearch.jsx
**on Blur**
⏬ ⏬ ⏬ 
**on Focus**
=> Select the text when input box is changed from blur to focus

components/x-follow-button/src/FollowButton.jsx
Adds an `onClick` prop to X-Follow-Button, looks like we don't have `prop-types`, so `if` will have to do
=> Added onClick prop to X-Follow-Button

readme.md
I think this project is out of the experimental phase, so removing this phrasing.
=> Remove "experiment"

.eslintignore, __tests__/snapshots.test.js
=> Support class components in story snapshot tests

__tests__/__snapshots__/snapshots.test.js.snap, components/x-audio/.bowerrc, components/x-audio/bower.json, components/x-audio/package.json, components/x-audio/src/components/Buttons.jsx, components/x-audio/src/components/index.jsx, components/x-audio/src/components/styles.scss, components/x-audio/src/redux/index.jsx, components/x-audio/stories/index.js
**Expanded**
**Minimised**
**Dummy**
- minimise button
- play icon 
- range bar for timeline
=> X audio grid layout & basic styles

__tests__/__snapshots__/snapshots.test.js.snap, components/x-audio/src/components/Buttons.jsx
* switched `title` for `aria-label` because `aria-label` doesn't have the issues `title` has
* added `aria-label` to the close button
=> Add aria-labels to buttons

__tests__/__snapshots__/snapshots.test.js.snap, components/x-audio/src/redux/__tests__/player-logic.test.js, components/x-audio/src/redux/index.jsx, components/x-audio/src/redux/player-logic.js
- Required to configure tracking, so that when new audio is played, tracking can be reconfigured
- Required for storybook (+ likely .com) so that when the page loads the URL can be set BUT the audio won't start playing
=> loadMedia action

components/x-audio/readme.md
Starter for ten for x-audio readme.
=> Flesh out x-audio readme

__tests__/__snapshots__/snapshots.test.js.snap, components/x-audio/src/redux/__tests__/__snapshots__/player-logic.test.js.snap, components/x-audio/src/redux/__tests__/player-logic.test.js, components/x-audio/src/redux/index.jsx, components/x-audio/src/redux/player-logic.js, components/x-audio/stories/knobs.js, components/x-audio/stories/redux-player.js
I accidentally lost all my commits  on `x-audio-modify-where-duration-from` by rebasing with `x-audio`.
@benbarnett  has the branch before I rebase, He saved my life.
This PR is the same as https://github.com/Financial-Times/x-dash/pull/299
=> Get duration by durationchange events

changelog.md
Change log was a few version out so updated in this PR.
=> bring changelog uptodate

components/x-audio/__tests__/x-audio.test.jsx, components/x-audio/src/components/ErrorMessage.jsx, components/x-audio/src/components/index.jsx, components/x-audio/src/redux/__tests__/__snapshots__/player-logic.test.js.snap, components/x-audio/src/redux/index.jsx, components/x-audio/src/redux/player-logic.js, components/x-audio/stories/expanded.js, components/x-audio/stories/knobs.js, components/x-audio/stories/minimised.js, package.json
* add handling for error event that will show a message to users
* allow users to recover from a network failure resulting in an error that reloads the audio and starts it from where they left off
* also reset all the state when load media occurs
=> X audio error

components/x-audio/src/components/index.jsx, components/x-audio/src/redux/index.jsx
Use aria-label rather than title because it is better supported
=> X audio aria label

components/x-audio/src/components/index.jsx, components/x-audio/src/redux/index.jsx
* add the wip prop (from app policy)
=> Add persistent player wip flag to props

components/x-audio/readme.md
Add swimlane diagrams to x-audio's readme
=> Add swimlane diagrams

components/x-audio/src/components/Players.jsx, components/x-audio/src/components/rc-slider/Handle.jsx, components/x-audio/src/components/rc-slider/Slider.jsx, components/x-audio/src/components/rc-slider/common/Track.jsx, components/x-audio/src/components/rc-slider/common/createSlider.jsx, components/x-audio/src/components/rc-slider/utils.js, components/x-audio/src/components/styles.scss, components/x-audio/src/redux/__tests__/middleware/notifier.test.js
https://trello.com/c/qVTsnaIK/484-scrub-bar-do-not-seek-audio-when-user-touches-the-track
=> Do not seek audio when user touches the track

components/x-audio/__tests__/x-audio.test.jsx, components/x-audio/readme.md, components/x-audio/src/components/Image.jsx, components/x-audio/src/components/Players.jsx, components/x-audio/src/components/index.jsx, components/x-audio/src/components/styles.scss, components/x-audio/src/redux/index.jsx, components/x-audio/stories/redux-player.js
This PR is the same as https://github.com/Financial-Times/x-dash/pull/349
However some reason (I don't know the reason maybe circle side problem), the circle build of https://github.com/Financial-Times/x-dash/pull/349 doesn't pass.
=> Display image from props

components/x-audio/src/components/__tests__/__snapshots__/playback-rates.test.js.snap, components/x-audio/src/components/playback-rates.js
The playback becomes distorted and basically unlistenable.
=> Remove 2x option from speed control

components/x-audio/src/components/Players.jsx, components/x-audio/src/components/styles.scss
BEFORE --- 3 x 6
AFTER --- 1 x 7
=> Modify player design

components/x-audio/src/components/styles.scss
=> Hide image on mobile landscape

__tests__/__snapshots__/snapshots.test.js.snap, components/x-podcast-launchers/package.json, components/x-podcast-launchers/readme.md, components/x-podcast-launchers/src/PodcastLaunchers.css, components/x-podcast-launchers/src/PodcastLaunchers.jsx, components/x-podcast-launchers/stories/index.js
=> Add Styles

__tests__/__snapshots__/snapshots.test.js.snap, components/x-podcast-launchers/src/PodcastLaunchers.jsx, components/x-podcast-launchers/src/__tests__/__snapshots__/PodcastLaunchers.test.jsx.snap, components/x-podcast-launchers/src/__tests__/__snapshots__/generate-app-links.test.js.snap, components/x-podcast-launchers/src/app-links.js
Adds data-trackable attributes for clicking tracking.
```
apple-podcasts
overcast
pocket-casts
podcast-addict
acast
copy-rss
```
=> Add data trackable

__tests__/__snapshots__/snapshots.test.js.snap, components/x-podcast-launchers/package.json, components/x-podcast-launchers/readme.md, components/x-podcast-launchers/src/PodcastLaunchers.jsx, components/x-podcast-launchers/src/PodcastLaunchers.scss, components/x-podcast-launchers/src/__tests__/PodcastLaunchers.test.jsx, components/x-podcast-launchers/src/__tests__/__snapshots__/PodcastLaunchers.test.jsx.snap, components/x-podcast-launchers/src/copy-to-clipboard.js, components/x-podcast-launchers/stories/example.js, components/x-podcast-launchers/stories/knobs.js
=> Add headings and follow button

__tests__/__snapshots__/snapshots.test.js.snap, components/x-podcast-launchers/src/PodcastLaunchers.jsx, components/x-podcast-launchers/src/__tests__/__snapshots__/PodcastLaunchers.test.jsx.snap
=> Pass renderFollowButton from props

.storybook/register-components.js, __tests__/__snapshots__/snapshots.test.js.snap, changelog.md, components/x-audio/package.json, components/x-audio/src/redux/index.jsx, components/x-audio/src/redux/tracking.js, components/x-podcast-launchers/.bowerrc, components/x-podcast-launchers/.npmignore, components/x-podcast-launchers/bower.json, components/x-podcast-launchers/package.json, components/x-podcast-launchers/readme.md, components/x-podcast-launchers/rollup.js, components/x-podcast-launchers/src/PodcastLaunchers.jsx, components/x-podcast-launchers/src/PodcastLaunchers.scss, components/x-podcast-launchers/src/__tests__/PodcastLaunchers.test.jsx, components/x-podcast-launchers/src/__tests__/__snapshots__/PodcastLaunchers.test.jsx.snap, components/x-podcast-launchers/src/__tests__/__snapshots__/generate-app-links.test.js.snap, components/x-podcast-launchers/src/__tests__/generate-app-links.test.js, components/x-podcast-launchers/src/__tests__/generate-rss-url.test.js, components/x-podcast-launchers/src/config/app-links.js, components/x-podcast-launchers/src/config/series-ids.js, components/x-podcast-launchers/src/copy-to-clipboard.js, components/x-podcast-launchers/src/generate-app-links.js, components/x-podcast-launchers/src/generate-rss-url.js, components/x-podcast-launchers/stories/example.js, components/x-podcast-launchers/stories/index.js, components/x-podcast-launchers/stories/knobs.js
- Add rootContentId to audio events
- upgrades to `o-audio beta 12`
=> Add rootContentId to tracking context

components/x-podcast-launchers/bower.json, components/x-podcast-launchers/readme.md, components/x-podcast-launchers/src/PodcastLaunchers.scss
As part of the Origami cascade, bump o-typography, o-forms and o-buttons to new majors.
=> X podcast launcher cascade

components/x-podcast-launchers/src/PodcastLaunchers.scss
Add missing scale arg to oTypography call
=> Fix scale arg

components/x-teaser/__fixtures__/video.json, components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap, components/x-teaser/readme.md, components/x-teaser/src/Video.jsx, components/x-teaser/storybook/index.js, components/x-teaser/storybook/video.js
This PR fixes the one issue I've found with the latest Origami versions, and bumps the dependencies in Storybook.
The one problem I came across is video no longer working as it required a system code. I have added this as a prop, and set it in storybook, and documented it.
=> Origami cascade x teaser

components/x-content-block/.bowerrc, components/x-content-block/bower.json, components/x-content-block/package.json, components/x-content-block/src/ContentBlock.jsx, components/x-content-block/src/ContentBlock.scss
This is my attempt at adding styling to our component. See x-dash documentation:
https://financial-times.github.io/x-dash/docs/components/styling
=> Add styling using Origami component

components/x-privacy-manager/src/__tests__/privacy-manager.test.jsx, components/x-privacy-manager/src/privacy-manager.jsx
Added integration with `next-consent-proxy` for enhanced experience only
Further work in the tests is needed
=> Added first useful version of consent-proxy request

components/x-privacy-manager/readme.md
Update privacy-manager props in README to latest changes
=> Update privacy-manager docs

changelog.md
In advance of a minor release 1.1.0 of x-dash, update the changelog to reflect the addition of `x-privacy-manager`
=> Version 1.1.0

changelog.md
=> Version 1.1.1

changelog.md
Added release notes for version 1.1.3
=> Version 1.1.3

components/x-live-blog-post/readme.md
Updates the readme with correct information about what the component displays.
=> x-live-blog-post update readme

__tests__/__snapshots__/snapshots.test.js.snap, components/x-gift-article/src/CopyConfirmation.jsx
Addresses DAC issue detailed in https://financialtimes.atlassian.net/browse/ACC-431
Adds `role="alert"` to containing block of copyConfirmation.jsx component to alert Assistive technology(AT) to a visual change in the UI.
=> ACC-431-copy-status-copy-message

__tests__/__snapshots__/snapshots.test.js.snap, components/x-gift-article/src/Buttons.jsx, components/x-gift-article/src/GiftArticle.scss, docs/components/release-guidelines.md
- Improved the description of Email Link in Gift Article to be clearer for screen reader users. 
- Improved the releasing instructions to be more newcomer friendly.
=> ACC-430 Improved the description of Email Link in Gift Article

components/x-live-blog-post/readme.md, components/x-live-blog-post/src/LiveBlogPost.jsx, components/x-live-blog-post/src/__tests__/LiveBlogPost.test.jsx, components/x-live-blog-post/storybook/index.jsx
FT app is using native sharing, so we want to hide the share buttons when using this component in the app.
=> x-live-blog-post option for hiding share buttons

changelog.md
Update to changelog to reflect changes made in PR #480, #482 and #484
=> Version 1.1.4

CODEOWNERS, changelog.md, components/x-privacy-manager/package.json, components/x-privacy-manager/src/__tests__/privacy-manager.test.jsx, components/x-privacy-manager/src/messages.jsx, components/x-privacy-manager/src/privacy-manager.jsx, components/x-privacy-manager/src/privacy-manager.scss, components/x-privacy-manager/src/radio-btn.jsx, components/x-privacy-manager/src/radio-btn.scss, components/x-privacy-manager/src/types.d.ts, package.json
This PR rolls up several small commits addressing content changes and bug fixes.
It may be easier to review commit-by-commit:
- Codeowners: https://github.com/Financial-Times/x-dash/commit/60cd91ebed5abbbd8daa2e9c6681b923481f3019
- Content: https://github.com/Financial-Times/x-dash/commit/c4f19025408bd3cde5e2e3e834e7fca10012b657
- Bugfixes: https://github.com/Financial-Times/x-dash/commit/49f8087769af3412d6c68c036cd93c0bfc428781
=> X privacy manager v1.0.1

changelog.md, components/x-live-blog-post/package.json
Changelog and versioning changes for `x-live-blog-post`.
=> Version 1.2.0

changelog.md
Includes only changes to `x-privacy-manager`
=> Version 1.3.0

__tests__/__snapshots__/snapshots.test.js.snap, components/x-gift-article/src/Message.jsx, components/x-gift-article/stories/index.js, components/x-gift-article/stories/with-gift-link.js
Change message for gift articles
Ticket: https://financialtimes.atlassian.net/browse/ACC-332
- **Must** be tested in FT.com and Apps before merge
I've also added a missing Storybook, screenshot below:
=> ADD-332: Update article gift link message

components/x-privacy-manager/src/messages.jsx
A simple message change as requested in [this ticket](https://financialtimes.atlassian.net/browse/ADSDEV-566). 
It could make sense to release as a minor update. Thoughts?
=> Changed message in x-privacy-manager component

components/x-live-blog-wrapper/src/LiveEventListener.js
Connects to `next-live-events-api` v2 endpoint for live updates.
=> Use next-live-event-api v2 endpoint to listen to live updates

components/x-live-blog-wrapper/src/LiveBlogWrapper.jsx, components/x-live-blog-wrapper/src/__tests__/LiveBlogWrapper.test.jsx
This will improve performance and memory usage.
=> Modify posts array instead of creating a new array when updating state

components/x-live-blog-wrapper/package.json, components/x-live-blog-wrapper/readme.md
Adds information about;
* Rendering the component at the server side
* Hydrating the component at the client side
* Live updates
* Client side events
=> Update readme with usage instructions

CODEOWNERS
Change ownership of x-gift-article
Ticket: https://financialtimes.atlassian.net/browse/ACC-640
=> ACC-640: Change ownership for x-gift-article

components/x-teaser/__fixtures__/promoted.json, components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap, components/x-teaser/package-lock.json, components/x-teaser/src/Promoted.jsx
"by" should be included within the markup before the
`o-teaser__promoted-by` element.
This will require projects update `n-native-ads` to avoid a
duplicate "by" https://github.com/Financial-Times/n-native-ads/pull/102
=> Correct promoted teaser markup.

CODEOWNERS, components/x-live-blog-wrapper/src/LiveBlogWrapper.jsx, components/x-live-blog-wrapper/src/__tests__/LiveBlogWrapper.test.jsx
New posts will appear on top
[Jira ticket](https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1153&projectKey=CI&modal=detail&selectedIssue=CI-351)
=> Order live blog posts by date

.circleci/config.yml
This reverts commit 7debe342de326e0f39e5452c94146fb1bac96143.
=> Revert "Remove snyk from publish step in CircleCI temporarily"

.circleci/config.yml, components/x-gift-article/readme.md, components/x-interaction/package.json, components/x-interaction/readme.md, components/x-live-blog-post/package.json, components/x-live-blog-post/readme.md, components/x-live-blog-wrapper/package.json, components/x-live-blog-wrapper/readme.md, components/x-podcast-launchers/package.json, components/x-podcast-launchers/readme.md, components/x-privacy-manager/package.json, components/x-privacy-manager/readme.md, components/x-styling-demo/package.json, components/x-teaser-timeline/package.json, components/x-teaser-timeline/readme.md, components/x-teaser/package.json, components/x-teaser/readme.md, docs/get-started/installation.md, packages/x-engine/package.json, packages/x-engine/readme.md, packages/x-handlebars/package.json, packages/x-handlebars/readme.md, packages/x-node-jsx/package.json, packages/x-node-jsx/readme.md, packages/x-rollup/src/rollup-config.js, private/blueprints/component/package.json, private/blueprints/component/readme.md
This update is made incorporating the points raised by @simonplend in this issue: https://github.com/Financial-Times/tooling-helpers/issues/60.
Essentially, if we aim to support (or state compatibility for) the packages on multiple Node versions then we should be testing the packages on all of those Node versions as part of the CI process accordingly. However, that would result in very protracted build times.
The benefit of having made the Node upgrades across Customer Products so that all apps are on the same version (v12) is that we only need to worry about supporting packages on a single Node version. I have checked with @rowanbeentje and all the FT App repos that consume `x-dash` are also all on Node v12.
This PR amends various Node values and README statements to make clear that only …
=> Update to Node v12

.circleci/config.yml
Undoing this PR: https://github.com/Financial-Times/x-dash/pull/552
=> Re-add Snyk command

.circleci/config.yml
I have published my latest changes and reintroducing the Snyk command. Fingers crossed we are close to a fix for the Snyk error!
Reverts Financial-Times/x-dash#555
=> Revert "Remove failing Snyk CircleCI command"

components/x-interaction/__tests__/serialiser.test.js, components/x-interaction/readme.md
=> CPP-465 Added tests for serialiser.js

.circleci/config.yml, .eslintignore, .gitignore, components/x-interaction/readme.md, e2e/app.js, e2e/common.js, e2e/e2e.test.js, e2e/index.js, e2e/jest.e2e.config.js, e2e/package.json, e2e/webpack.config.js, package.json
runs a real express app in the e2e test, which involves creating a SSR button that is hydrated (ie. event listener added to the SSR template). puppeteer clicks the button to show that the component is properly hydrated. this gif illustrates it:
https://user-images.githubusercontent.com/20088576/134715395-be9a46af-90f8-4e3d-a2ea-259c3888209d.mov
=> CP-465 Added e2e test for hydration and serialisation

components/x-live-blog-wrapper/readme.md, components/x-live-blog-wrapper/src/LiveBlogWrapper.jsx, components/x-live-blog-wrapper/src/__tests__/post-tracker.test.js, components/x-live-blog-wrapper/src/lib/post-tracker.js, components/x-live-blog-wrapper/storybook/index.jsx
The implementation of post level tracking for live blogs was previously done on `next-article`. As part of the process of implementing post level tracking on `ft-app`, the implementation of post-tracker has been moved to the `x-live-blog-wrapper` component. With this implementation, a new property (object) has been added to `x-live-blog-wrapper` component called `postTrackerConfig` (with the following properties/fields `onEntersViewport` [callback function], `onRead` [callback function], `onError` [callbackfunction], `usePostTracker` [boolean]).
The post-tracker class creates an intersection-observer instance and observes the visibility of posts that exist in the live-blog-wrapper component. When a new post is inserted, the wrapper component dispatches an event. The post tracker class …
=> Ci 890 live blog post tracker

.storybook/main.js, components/x-privacy-manager/package-lock.json, components/x-privacy-manager/package.json, components/x-privacy-manager/src/__tests__/helpers.js, components/x-privacy-manager/src/__tests__/messaging.test.jsx, components/x-privacy-manager/src/__tests__/state.test.jsx, components/x-privacy-manager/src/components/form.jsx, components/x-privacy-manager/src/components/messages.jsx, components/x-privacy-manager/src/privacy-manager.jsx, components/x-privacy-manager/src/privacy-manager.scss, components/x-privacy-manager/storybook/data.js, components/x-privacy-manager/typings/x-privacy-manager.d.ts
When a user's choice has been saved we display an onward link. This change allows us to make it point back to the page from which they came.
Additionally, this PR moves the confirmation message to the area below the form controls to make the progression clearer to users.
=> Add support for redirectUrl prop in place of referrer

components/x-teaser-timeline/package.json, components/x-teaser-timeline/src/lib/transform.js, components/x-teaser-timeline/typings/x-teaser-timeline.d.ts
Moves type definitions into a dedicated definitions file
=> ADSDEV 963/externalise type definitions

components/x-follow-button/package.json, components/x-gift-article/package.json, components/x-live-blog-post/package.json, components/x-podcast-launchers/package.json, components/x-privacy-manager/package.json, components/x-teaser-timeline/package.json, components/x-topic-search/package.json
a) it doesn't work because bootstrapping b) they get built in order after install anyway
=> don't build individual components on install

components/x-gift-article/src/ReferAFriend.scss
Had a not committed change on this feature's PR 😞 
https://financialtimes.atlassian.net/browse/RS-17
| Before | After |
| ------ | ----- |
|![Screenshot 2022-07-27 at 10 19 10](https://user-images.githubusercontent.com/1725956/181199962-85b5f6af-90bd-443f-a710-64b5e83caefc.png)|![Screenshot 2022-07-27 at 10 24 46](https://user-images.githubusercontent.com/1725956/181200016-5857964a-2936-4ee7-9ce0-80ed28184abf.png)|
=> Fix gift icon spacing

components/x-live-blog-post/src/ShareButtons.jsx
[https://financialtimes.atlassian.net/browse/CI-1362](https://financialtimes.atlassian.net/browse/CI-1362)
=> [CI-1362] show title in arial-label attribute for every share button

packages/x-engine/src/server.js
ht @nickramsbottom for pointing out the current unhelpful message
=> fix: improve x-engine server error message

components/x-follow-button/package.json, components/x-follow-button/src/FollowButton.jsx, components/x-follow-button/storybook/index.jsx
The inverse-monochrome theme has been added to the follow button in n-myft-ui - this PR updates the x-follow-button to support this
=> Update x-follow-button to support inverse monochrome

components/x-gift-article/readme.md
As part of this ticket [ACC-2308](https://financialtimes.atlassian.net/browse/ACC-2308) we decided to add a small clarification about what is a gift article
[ACC-2308]: https://financialtimes.atlassian.net/browse/ACC-2308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ACC-2308: add extra clarification to readme

components/x-gift-article/readme.md
- set the Project to `Automated kanban with reviews`, but remove the `To Do` column
- If you're not …
=> ENTST-561: update x-gift-article README

components/x-interaction/__tests__/serialiser.test.js, components/x-interaction/src/concerns/serialiser.js
serialiser? i hardly know 'er!
=> fix: improve serialiser error messages

components/x-gift-article/src/FooterMessage.jsx
- set the Project to `Automated kanban with reviews`, but remove the `To Do` column
- If you're not …
=> ENTST-664: update "Send to multiple people with Advanced Sharing" link

components/x-gift-article/src/ShareArticleDialog.scss
- Added comment to the close button style
=> Add comment about o-overlay

components/x-gift-article/__tests__/x-gift-article.test.jsx, components/x-gift-article/src/AdvancedSharingBanner.jsx, components/x-gift-article/src/Header.jsx, components/x-gift-article/src/ShareArticleDialog.scss, components/x-gift-article/src/SocialShareButtons.jsx
- Updated the headings hierarchy
- Updated the styles of the headings to match the previous design
=> Update headings in AS modal

components/x-gift-article/src/ShareArticleDialog.jsx
- Added `aria-modal` to indicate that the sharing dialog is a modal.
=> Added aria-modal

components/x-gift-article/src/lib/share-link-actions.js
In this PR, the pre-fill email copy for sharing is modified with a little bit different subject and body.
Related JIRA ticket: [ELES-1090](https://financialtimes.atlassian.net/jira/software/c/projects/ELES/boards/1628?selectedIssue=ELES-1090)
| Before | After |
| ------- | ------- |
| ![image](https://github.com/Financial-Times/x-dash/assets/73290490/2d0d42ef-6ea5-445f-97bb-b1a0c18ed6cf) | ![image](https://github.com/Financial-Times/x-dash/assets/73290490/cbd01e0e-6589-42d7-8095-1a6eff34968d) |
[ELES-1090]: https://financialtimes.atlassian.net/browse/ELES-1090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ELES-1090 Pre-fill email copy for Sharing

.storybook/preview-head.html
I know this is a little pointless but it's gonna keep getting noticed. Let's tidy up.
=> Remove the polyfill service

components/x-gift-article/__tests__/x-gift-article.test.jsx, components/x-gift-article/src/GiftArticle.jsx, components/x-gift-article/src/IncludeHighlights.jsx, components/x-gift-article/src/ShareArticleDialog.scss, components/x-gift-article/src/SocialShareButtons.jsx, components/x-gift-article/src/lib/highlightsHelpers.js, components/x-gift-article/src/lib/share-link-actions.js, components/x-gift-article/src/lib/updaters.js, components/x-gift-article/storybook/share-article-modal-b2b-highlights.jsx, components/x-gift-article/storybook/share-article-modal-b2b-save-highlights-message.jsx, components/x-gift-article/storybook/share-article-modal-with-advanced-sharing-free-article.jsx, components/x-gift-article/storybook/share-article-modal-with-advanced-sharing-no-both-credits.jsx, components/x-gift-article/storybook/share-article-modal-with-advanced-sharing-no-enterprise-credits.jsx, components/x-gift-article/storybook/share-article-modal-with-advanced-sharing-no-gift-credits.jsx, components/x-gift-article/storybook/share-article-modal-with-advanced-sharing-save-highlights-message.jsx, components/x-gift-article/storybook/share-article-modal-with-advanced-sharing.jsx
This PR adds the highlights preview to the x-gift-article modal
[ELES-1333]: https://financialtimes.atlassian.net/browse/ELES-1333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ELES-1333  add highlight preview to x-article-gift

components/x-privacy-manager/jsconfig.json, components/x-privacy-manager/package.json, components/x-privacy-manager/readme.md, components/x-privacy-manager/rollup.js, components/x-privacy-manager/src/__tests__/config.test.jsx, components/x-privacy-manager/src/__tests__/helpers.js, components/x-privacy-manager/src/__tests__/messaging.test.jsx, components/x-privacy-manager/src/__tests__/state.test.jsx, components/x-privacy-manager/src/__tests__/utils.test.js, components/x-privacy-manager/src/actions.js, components/x-privacy-manager/src/components/form.jsx, components/x-privacy-manager/src/components/messages.jsx, components/x-privacy-manager/src/components/radio-btn.jsx, components/x-privacy-manager/src/components/radio-btn.scss, components/x-privacy-manager/src/privacy-manager.jsx, components/x-privacy-manager/src/privacy-manager.scss, components/x-privacy-manager/src/utils.js, components/x-privacy-manager/storybook/data.js, components/x-privacy-manager/storybook/index.jsx, components/x-privacy-manager/storybook/stories/consent-accepted.js, components/x-privacy-manager/storybook/stories/consent-blocked.js, components/x-privacy-manager/storybook/stories/consent-indeterminate.js, components/x-privacy-manager/storybook/stories/legislation-ccpa.js, components/x-privacy-manager/storybook/stories/legislation-gdpr.js, components/x-privacy-manager/storybook/stories/save-failed.js, components/x-privacy-manager/storybook/story-container.jsx, components/x-privacy-manager/typings/internal.d.ts, components/x-privacy-manager/typings/x-privacy-manager.d.ts, package-lock.json
it proved to hard to unpick where it's being used in `ft-app` and it causes peer dep conflicts so
probably easiest to review commit-by-commit
=> Reinstate and migrate x-privacy-manager

components/x-teaser-timeline/src/TeaserTimeline.scss
Description:
removed duplicated border bottom on x-teaser-timeline
slack conversation:
https://financialtimes.slack.com/archives/C07PT7A1LNB/p1746523695991769
=> remove duplicated x-teaser border bottom

components/x-follow-button/package.json, package-lock.json
Upgrading n-myft-ui version to 39.0.0
As part of updating the next-myft-client version across all dependent apps.
=> [CON-3890] Upgrade n-myft-ui version in x-follow-button to 39.0.0

CODEOWNERS
Update codeowners file
https://financialtimes.atlassian.net/jira/software/c/projects/CON/boards/1061?selectedIssue=CON-4013
=> CON-4013 Update CODEOWNERS

components/x-follow-button/package.json, package-lock.json
Upgrading n-myft-ui version to 40.0.0
As part of updating the next-myft-client version across consumer apps
=> Upgrade n-myft-ui version in x-follow-button to 40.0.0
