Financial-Times/x-dash

- components/x-interaction/src/InteractionClass.jsx
it's passed in via the toplevel function. having it here is misleading
> Remove initialState from actions

- jest.config.js
Adds the `testURL` property to the Jest config. To fix the following error with the latest version of JSDom. (Further details https://github.com/facebook/jest/issues/6766)
```
FAIL
● Test suite failed to run
SecurityError: localStorage is not available for opaque origins at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
at Array.forEach (<anonymous>)
```
> add testURL property

- tools/x-docs-2/src/components/layouts/basic.jsx
- tools/x-docs-2/src/components/sidebar/module-list.jsx
- tools/x-docs-2/src/lib/create-npm-package-pages.js
- tools/x-docs-2/src/templates/npm-package.jsx
- tools/x-docs-2/static/main.css
Displays subheadings on the sidebar, like this:
Gets markdown information via query using `allMarkdownRemark` function, and then displays it in relevant places.
- Any depth is displayed, let's hope if stays visually appealing
- Every subheading is a link to corresponding part of the text (transitions are smoooooth)
- We can see subheadings of the active heading only
> Display subheadings on the sidebar

- __tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/src/Title.jsx
so the title can be supplied as a component, as per https://github.com/Financial-Times/x-dash/issues/124#issuecomment-414339312
if the feature of string coercion was not documented, then this would be a patch version.
--
edit: @i-like-robots says it's possible the whitespace isn't needed anymore at all. i'll confirm this locally and supply another commit if that's the case.
> Don't coerce `displayTitle` to a string

- __tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/src/concerns/presets.js
- components/x-teaser/stories/knobs.js
🐿 v2.10.2
Most or all of the teasers in use on FT.com _should_ be using relative time. The reasons for this is:
* Homepage because most of the content will be from that day
* Streams have the date on the left hand side (grouping the articles)
* Life and arts page has no dates because the content is more everlasting, so showing the date may make it look stale.
* Possible exception might be article related links?
But since the majority will be using relative time, this PR sets `useRelativeTime` to true for all the presets.
> Use relative time for all the preset teasers

- components/x-teaser/Props.d.ts
- components/x-teaser/readme.md
- components/x-teaser/src/concerns/constants.js
- components/x-teaser/stories/knobs.js
🐿 v2.10.2
Adds a new image size of width 1180px (which is the max width the content goes on www.ft.com).
The large hero image on https://www.ft.com/life-arts is full width, and looks bad with a 640px image.
Not making XXL the preset size for HeroOverlay because it's also used in smaller contexts.
> Add XXL as an image size

- components/x-teaser/src/RelativeTime.jsx
Add a space after the prefix text for relative timestamps, as they are currently bunched together.
Is currently:
> Add space after relative time prefix

- packages/x-engine/readme.md
_**This is a documentation change.**_
This adds documentation describing how to configure [n-ui](https://github.com/Financial-Times/n-ui) to compile `x-engine` based `.jsx` files for use on the client side.
Because [n-ui](https://github.com/Financial-Times/n-ui) means that consuming projects webpack configs are a step removed from them, it means that these project require a slightly different configuration.
In order to configure n-ui to compile x-dash based `.jsx` files you will also need to add the following to `n-ui-build.config.js`.
```js
// n-ui-build.config.js
const xEngine = require('@financial-times/x-engine/src/webpack');
module.exports = {
plugins: [
xEngine()
],
pragma: 'h'
};
```
You will also need to import `h` from `x-engine` at the top of each `.jsx` file.
```javascript …
```
> Document how to configure `n-ui` to support `x-engine` .jsx files on the client side

- docs/components/stories.md
Simple documentation to describe using fetch-mock for stories.
Following https://github.com/Financial-Times/x-dash/pull/181#discussion_r220573438
> Include documentation for mocking http requests

- components/x-teaser/Props.d.ts
- components/x-teaser/readme.md
- components/x-teaser/stories/knobs.js
ES Interface isPodcast indicator:
https://github.com/Financial-Times/next-es-interface/blob/8982c96c901dd9e95df5846e27297defc7211395/server/transformers/plugins/audio/teaser.js#L15
> Add isPodcast indicator

- components/x-topic-search/src/TopicSearch.jsx
To update `followedTopics` after clicking myFT follow buttons, add topicFollowed/topicUnfollowed actions which are triggered externally.
https://financial-times.github.io/x-dash/components/x-interaction#triggering-actions-externally
> Add topicFollowed/topicUnfollowed externally triggered actions

- components/x-topic-search/__tests__/__snapshots__/x-topic-search.test.jsx.snap
- components/x-topic-search/__tests__/x-topic-search.test.jsx
- components/x-topic-search/readme.md
- components/x-topic-search/src/AllFollowed.jsx
- components/x-topic-search/src/SuggestionList.jsx
- components/x-topic-search/src/TopicSearch.jsx
- components/x-topic-search/src/lib/get-suggestions.js
- components/x-topic-search/stories/topic-search.js
This change is to update followedTopics properly when users click an external follow button. x-topic-search executes the topicFollowed action (which is triggered in the consumer side) when that happens. x-topic-search gets only the topic id from the event, but it needs the whole topic data to render correct info.
Changing from **Fetch suggestions except followedTopics** to **Fetch all suggestions and then pick followedTopic up by the ids** will make easier to update followedTopics with the whole topic data.
> Fetch suggestions include followed topics

- __tests__/__snapshots__/snapshots.test.js.snap
- components/x-topic-search/readme.md
- components/x-topic-search/src/TopicSearch.jsx
Can't click follow button in topic search result because the result disappears (this happens because of `onBlur` on `<input>`). Hiding the result container need to be controled by external triggers.
> Remove onBlur which hides result

- __tests__/__snapshots__/snapshots.test.js.snap
- components/x-topic-search/__tests__/__snapshots__/x-topic-search.test.jsx.snap
- components/x-topic-search/src/TopicSearch.jsx
The autocomplete list overlaps x-topic-search suggestion list.
> Disable input box's autocomplete

- components/x-topic-search/src/TopicSearch.scss
The search cancel button is supported only in WebKit and Blink, hence the vendor prefix `::-webkit-` is needed.
**BEFORE**
**AFTER**
> Apply custom styles to search cancel button

- components/x-topic-search/src/TopicSearch.scss
I accidentally deleted the branch and closed this PR... https://github.com/Financial-Times/x-dash/pull/245 🙈 
**The bug**
-----
Only on Safari, the input box's height is set differently.
Chrome, Firefox, IE11 => 40px
Safari => 46px
**The reason**
-----
It seems Safari includes the height of search cancel button as the input height and Chrome doesn't.
```css
input {
min-height: 40px;
padding: 9px 9px 9px;
font-size: 16px;
line-height: 20px;
margin: 0;
border-bottom: 2px solid #ffffff;
padding-left: 24px;
&::-webkit-search-cancel-button {
@include oIconsGetIcon('cross', oColorsGetPaletteColor('white'), 26);
-webkit-appearance: none;
}
}
```
**The solution**
-----
Adding `position: absolute` or `z-index` doesn't solve the problem. Overwrite padding top/bottom 0 and keep the input height the …
> Fix wrong input height on Safari

- components/x-topic-search/bower.json
- components/x-topic-search/src/TopicSearch.scss
@i-like-robots's comment on this PR https://github.com/Financial-Times/x-dash/pull/246
Thank you, @i-like-robots 🙇‍♀️ 
>Just a note on something I noticed, I don't expect it to be addressed in this PR... I see that this component is using some styles from o-forms, but I can't see that the design has much commonality with o-forms and that many of the styles are being overwritten. I'd be tempted to try .input { font: inherit; } as the base and go from there.
> Remove o-forms

- __tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/stories/podcast.js
This reflects the change we made to next-es-interface to use a different image for podcasts when in a teaser
> Update data for podcast teaser

- components/x-teaser/src/Title.jsx
- components/x-teaser/stories/index.js
To update `o-teaser`, `o-labels` has to be updated. There was a breaking change where label class names were changed so the premium label in `x-teaser` was changed from `.premium` to `.content-premium`
> Update o-labels dependency and HTML template

- readme.md
we probably don't need the screenreader to say "x-dash" twice
> remove alt attr

- package.json
- packages/x-babel-config/index.js
- packages/x-babel-config/package.json
- packages/x-rollup/package.json
- packages/x-rollup/src/babel-config.js
- tools/x-ssr-demo/package.json
The current version includes a vulnerable version of the `braces` dependency.
https://app.snyk.io/vuln/npm:braces:20180219
> chore(deps): upgrade to babel-jest v24

- __tests__/__snapshots__/snapshots.test.js.snap
- components/x-audio/src/components/Buttons.jsx
- components/x-audio/src/components/index.jsx
- components/x-audio/src/redux/index.jsx
- components/x-audio/src/redux/player-logic.js
- components/x-audio/stories/expanded.js
- components/x-audio/stories/knobs.js
- components/x-audio/stories/minimised.js
Wire up x-audio so it can be manipulated by its consumers.
In this case the playing state will be managed by ft-app redux: https://github.com/Financial-Times/ft-app/pull/248
> Hook up Play + Pause actions to the app

- __tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/src/Title.jsx
After discussing it with @chee 
An extra space is inserted after the title text on teaser titles, it is apparently serving as a workaround to an issue where the labels weren't displayed correctly. 
This is now causing issue with the "external link" icon on promoted content teasers. Where the icon overlaps the text, and this weird behaviour seems to be linked to this extra space.
I ran x-teaser with premium labels and without the space, it doesn't change anything visually, it seems safe to remove this workaround now
> Remove extra space after title text

- components/x-audio/.bowerrc
- components/x-audio/__tests__/x-audio.test.jsx
- components/x-audio/bower.json
- components/x-audio/package.json
- components/x-audio/readme.md
- components/x-audio/src/components/Loading.jsx
- components/x-audio/src/components/classnames-helper.js
- components/x-audio/src/components/index.jsx
- components/x-audio/src/components/styles.scss
- components/x-audio/src/redux/player-logic.js
- components/x-audio/stories/index.js
***this PR supersedes https://github.com/Financial-Times/x-dash/pull/280 (I have done on a separate branch as it was written by @debugwand, I wanted to make sure the original changes were still in tact)***
x-audio load component
* shows under the various loading events, waiting and stalled
* removed when canplay event fires
* dark when expanded mode, light when minimised
* expecting to inherit colours and background colours from containers
also:
* bower added so we can use typography mixins
* `x-audio` added as a keyword in package json so we can build locally with `athloi run build --filter 'keywords:"x-audio"'` instead of building everything
* `x-test-utils` and our first test file
> x-audio loading component

- components/x-increment/package.json
- components/x-interaction/package.json
- components/x-styling-demo/package.json
- components/x-teaser/.npmignore
- components/x-teaser/package.json
from conversation with @pavelpichrt: Apps Team would like to be able to use their own webpack configuration for x-dash components, to interoperate with their CSS modules configuration and other tooling. Previously, x-teaser'ds source files were being excluded by the npmignore, preventing this.
This PR also adds the `source` field to every component, allowing tooling to pick up on it and do e.g. for webpack:
```js
{
resolve: {mainFields: ['source', 'browser', 'module', 'main']}}
}
```
allowing `import {Teaser} from '@financial-times/x-teaser'` to load the source JSX
> expose source files in packages

- components/x-audio/src/components/TimeRemaining.jsx
For minimised player
I have confirmed with designer Luke, it should keep displaying "1 mins remaining" when the remaining is less than 1 mins
https://github.com/Financial-Times/x-dash/pull/289#discussion_r282922673
- Change `Math.floor()` => `Math.round()`
- Keep "1 mins remaining" when the remaining is less than 1 mins
> Keep 1 mins remaining  when it is less than 1 mins

- components/x-audio/src/redux/__tests__/__snapshots__/player-logic.test.js.snap
- components/x-audio/src/redux/__tests__/player-logic.test.js
- components/x-audio/src/redux/index.jsx
- components/x-audio/src/redux/player-logic.js
Adds an `ended` notifier that can be used by the consumer.
For example, the app will use this to close the player when audio has finished playing in the minimised state.
> Add an `ended` notifier so consumers can respond to this event

- components/x-audio/package.json
- components/x-audio/src/redux/__mocks__/@financial-times/o-audio.js
- components/x-audio/src/redux/__tests__/player-logic.test.js
- components/x-audio/src/redux/index.jsx
- components/x-audio/src/redux/player-logic.js
- components/x-audio/src/redux/tracking.js
- components/x-audio/stories/knobs.js
- components/x-audio/stories/redux-player.js
So we maintain the same audio tracking events as the current audio player has, we need to hook up the o-audio library.
This adds a new prop `trackingContext` which looks like:
```
trackingContext: PropTypes.shape({
contentId: PropTypes.string,
playerType: PropTypes.string,
audioSubtype: PropTypes.string
}).isRequired
```
The [Tracking](https://github.com/Financial-Times/o-audio/blob/master/src/js/tracking.js) class within o-audio is being pulled in explicitly.
> O audio integration

- components/x-teaser/src/Title.jsx
Reverts the change made in https://github.com/Financial-Times/x-dash/pull/282 with as slight amend so space is only applied when a premium content label is required.
Fixes part of the bug raised here: https://trello.com/c/CkoIA7pZ/889-padding-issue-with-topic-tracker-label
Following a discussion with Lee about amending this in o-tracker it was recommened that the fix was made in x-teaser: https://financialtimes.slack.com/archives/C02FU5ARJ/p1557917172106700
> reinstate space just for premium label

- components/x-audio/src/redux/player-logic.js
ensure text is always reset from error to loading regardless of when it was thrown
> Need to set error to false for load for recovery mid-stream

- components/x-audio/src/redux/middleware/notifier.js
This fixes the bug when the player doesn't automatically close when finished.
https://trello.com/c/wsnikIsM/451-minimised-audio-player-should-close-after-the-audio-has-ended
> Add the ended notifier to notifiers class

- __tests__/__snapshots__/snapshots.test.js.snap
- components/x-audio/src/components/TimeRemaining.jsx
To keep consistency with other place,
- the time next to play button on podcast pages on APP(min)
- in teasers(min)
- homepage podcast slice on ft.com(min)
**BEFORE**
**AFTER**
> Modify mins remaining => min remaining

- components/x-audio/src/redux/index.jsx
This is to fix a race condition where the close event is firing as soon as the close button is clicked, which results in the Redux state being cleared.
The tracking notifier is then run, which reports a `time_since_open` property. This is impossible to calculate because the time the player was opened is kept in Redux state, which has since been cleared.
So by moving the action into our own close button control, we can be sure the tracking notifier is called before we clear the state.
> Fire `WILL_CLOSE` action with onCloseClick, rather than on unmount

- components/x-audio/__tests__/format-seconds-to-hmmss.test.js
- components/x-audio/src/components/TimeRemaining.jsx
- components/x-audio/src/components/format-seconds-to-hmmss.js
> Do not display remaining time's decimal point

- components/x-audio/src/redux/index.jsx
`this.hasSwipeDownListener` was not working as what it should be. It's never reset the value once it was set. 
I missed this bug because expanded player behaves differently between ft-app and storybook. On ft-app it works fine(the detail below). However the ft-app behaviour is incorrect and also the `hasSwipeDownListener` value is incorrect anyway.
------
:confused: Weird behaviour on ft-app
When I change the player like the below, the player works differently between storybook and ft-app.
`minimised player` => `expanded player`1️⃣  => `minimised player` => `expanded player`2️⃣ 
**Storybook**
The expanded player 1️⃣  do swipe action.
The expanded player 2️⃣  doesn't do swipe action.
**ft-app**
The expanded player 1️⃣  do swipe action.
The expanded player 2️⃣  do swipe action.
I'm not sure …
> Fix expanded player not set swipe down

- components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/src/Image.jsx
This is a part of fixing DAC issues. Teasers from x-teaser provides tabable image links which leads repetitive navigation for the screen reader users.
The DAC trello ticket => https://trello.com/c/JCgvCagH/79-dacredundantlinksissue1
-----
On selecting image link(For ex: 'Extinction Rebellion...') and links(for ex: 'Extinction Rebellion: inside the new climate resistance') the sane page gets opened which leads to repetitive navigation for the screen reader user.
Similar issue has been observed on 'News article' page.
> Fix tabable image issue

- docs/integration/local-development.md
- makefile
- package.json
Convenience command so we can run commands like `make build-x-audio` to build just the x-audio component
> Build one cli

- components/x-audio/src/redux/__tests__/middleware/notifier.test.js
- components/x-audio/src/redux/index.jsx
- components/x-audio/src/redux/middleware/notifier.js
- components/x-audio/src/redux/player-logic.js
Example use case:
The app displays the expanded player in an overlay, which when clicked, should minimise the player.
> x-audio: Respond to external changes to expanded props

- components/x-audio/package.json
- package.json
**o-audio@v1.0.0-beta.11**
Add error property in tracking event.detail
This PR includes **Remove `tools/*` from workspaces** because I got this error on Circle builds.
`ENOENT: no such file or directory, stat '/home/circleci/project/build/tools/x-docs/static/storybook'`
https://circleci.com/gh/Financial-Times/x-dash/2944
I removed it not to be bothered by their errors, and also speed up the process of reinstalling and building as Matt H suggested on x channel on slack.
https://financialtimes.slack.com/archives/C10AJEQKS/p1560934866022200
I will add a note on x-audio branch to tell before merging into master we need to put back `tools/*` in `package.json`
> Update o-audio to v1.0.0-beta.11

- components/x-audio/src/redux/__tests__/player-logic.test.js
- components/x-audio/src/redux/player-logic.js
This should deal with the delaying in audio being played seen on iOS/Safari devices.
It seems to be that Safari doesn't honour the `audio.preload` attribute until `audio.load()` is called. In other browsers, setting `audio.src` is enough.
Current use case for x-audio is that the audio player is only shown after a user has requested to play audio, so preloading is ok here. In the future we may need to make this an option.
> Call audio.load() on LOAD_MEDIA action to trigger preloading

- components/x-audio/src/redux/__tests__/player-logic.test.js
- components/x-audio/src/redux/player-logic.js
This reverts commit 816c3e02e240c066d75ad21bb14bb40aa2b6c1a1.
Calling `audio.load()` at this stage was making Chrome thinking we were violating the autoplay policy.
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
> Revert "Call audio.load() on LOAD_MEDIA action to trigger preloading"

- components/x-audio/src/redux/__tests__/player-logic.test.js
- components/x-audio/src/redux/player-logic.js
Set x-audio state to loaded when we get the playing event from the audio object, as when events fire can happen in a different order to what you might expect when you fast forward
https://docs.google.com/spreadsheets/d/1lYdCJv74oyVhyHyoyZIR_Lh5TnuyNQ_cifOsvAnrGdU/edit#gid=747106634
> Also set state to loaded when playing

- components/x-audio/src/components/styles.scss
safari and iOS rendering of x-audio expanded mode had a display problem where long text was making the expanded player push beyond the edges of the window. Changing the grid column width unit from 1fr to 100% fixes this
> Column was too wide in expanded mode in safari and iOS app, fixed

- components/x-audio/src/components/TimeRemaining.jsx
- components/x-audio/src/components/__tests__/TimeRemaining.test.jsx
- components/x-audio/src/components/__tests__/__snapshots__/TimeRemaining.test.jsx.snap
iOS shows `-00:01` instead of a `-00:00` in time remaining when a show is finished. Andriod is OK.
With this solution, anything under 1 second is shown as `0:00`
> ensure 0ish time is always rendered as 00:00

- __tests__/__snapshots__/snapshots.test.js.snap
- components/x-podcast-launchers/readme.md
- components/x-podcast-launchers/src/PodcastLaunchers.css
- components/x-podcast-launchers/src/PodcastLaunchers.jsx
- components/x-podcast-launchers/src/copy-to-clipboard.js
`user-select: none;` is set in ft-app's body. Therefore `span` needs to be set `user-select: text;` otherwise it won't select the text to copy.
I have checked that this copy function works on Chrome, Safari, firefox and IE11.
> Add copyToClipboard function

- __tests__/__snapshots__/snapshots.test.js.snap
- components/x-podcast-launchers/src/__tests__/__snapshots__/PodcastLaunchers.test.jsx.snap
- components/x-podcast-launchers/src/__tests__/__snapshots__/generate-app-links.test.js.snap
- components/x-podcast-launchers/src/__tests__/generate-app-links.test.js
- components/x-podcast-launchers/src/app-links.js
- components/x-podcast-launchers/src/generate-app-links.js
- components/x-podcast-launchers/src/generate-rss-url.js
- components/x-podcast-launchers/stories/example.js
- The RSS URL should not be urlencoded when injected into the app links
- We should use `https` in the RSS URL, which will be set in the VAULT env var passed to the component, e.g. `https://acast.access.cloud`
- Pocketcasts, podcast addict + apple podcasts require the protocol to be stripped from the RSS URL
> Podcast link fixes

- __tests__/__snapshots__/snapshots.test.js.snap
- components/x-podcast-launchers/src/PodcastLaunchers.jsx
- components/x-podcast-launchers/src/PodcastLaunchers.scss
- components/x-podcast-launchers/src/__tests__/__snapshots__/PodcastLaunchers.test.jsx.snap
To make it easier to locate the buttons in spoor.
> Add additional data trackables around podcast launchers

- components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/src/MetaLink.jsx
So that the screen reader is slightly more verbose about where, for example, the link Argentina leads us, we now give it an aria-label which will say 'link, Category: Argentina'. This should make it clearer that the link takes you to ft.com/argentina.
> add aria label for categories

- components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/src/Title.jsx
Adds an aria-label property to all video and podcast teasers to include the phrase "Watch video" or "Listen to podcast" before the title attribute is read out. This will not affect other teasers as any attributes with a `null` value will be ignored.
This should be released as a new beta version: `v1.0.0-beta.17`
> Update the aria label on podcast and video teasers

- components/x-teaser/__fixtures__/top-story.json
- components/x-teaser/src/RelatedLinks.jsx
Replaces `url` with `relatedUrl` in the relatedLinks x-teaser component to more accurately match the data being passed in.
This change will affect the relatedLinks component only.
> update related links url property to relativeUrl

- components/x-teaser/src/RelatedLinks.jsx
Allows the relatedLinks x-teaser component to use either the `relatedUrl` or the `url` property if available. This brings the component more inline with other teaser components:
- https://github.com/Financial-Times/x-dash/blob/master/components/x-teaser/src/Image.jsx#L30
- https://github.com/Financial-Times/x-dash/blob/master/components/x-teaser/src/MetaLink.jsx#L26
This change will affect the relatedLinks component only.
> related content links can use url or relatedUrl as the href

- components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/src/Meta.jsx
- components/x-teaser/src/MetaLink.jsx
- components/x-teaser/src/Promoted.jsx
[This o-teaser PR](https://github.com/Financial-Times/o-teaser/pull/138) by Olga introduces flexbox to the meta tag.
It enforces no spacing from whitespace between tag children. 
When there is no whitespace it allows a tag, which is shorter 
than the width of the teaser, to wrap rather than overflow or 
break when alongside a prefix. But it would break x-dash 
implementations because of the extra wrapping elements.
The app is already [using this extra markup](https://github.com/Financial-Times/ft-app/blob/92c5799a00b3e82aa0aa13dc30d7b813cbd7f58d/lib/components/page/slots/weekend/styles.scss#L135) to override styles, 
which I'm happy to update before this is released. I think 
this approach is better than absorbing the extra markup 
into o-teaser.
> Remove markup not defined by o-teaser.

- components/x-teaser/readme.md
- components/x-teaser/src/Image.jsx
This PR adds an `imageDataUrl` boolean prop to x-teaser which can be used to indicate that the image URL provided is a self-contained image and the component does not have to construct an image URL or make a request to the origami image service.
The apps team are currently working on the capability to store images offline and consume them in teasers directly from this offline store. In order to make this work, we need x-teaser to accept images in data-url format and not to attempt to construct a URL for the image and request it from the origami image service. The new `imageDataUrl` prop achieves this.
I sense-checked this very briefly with Maggie before beginning - please let me know if there's anybody else I should assign to review!
> Add imageDataUrl prop to enable apps offline functionality

- __tests__/snapshots.test.js
This generates the same snapshot naming convention but goes along with eslint's demands.
```sh
27:12  error  First argument must be name  jest/valid-describe
```
> Satisfy eslint's describe() demands

- __tests__/__snapshots__/snapshots.test.js.snap
- components/x-podcast-launchers/bower.json
- components/x-podcast-launchers/readme.md
- components/x-podcast-launchers/src/PodcastLaunchers.jsx
- components/x-podcast-launchers/src/PodcastLaunchers.scss
- components/x-podcast-launchers/src/__tests__/__snapshots__/PodcastLaunchers.test.jsx.snap
- components/x-podcast-launchers/stories/index.js
This PR updates o-forms and o-buttons in the PodCast Launcher.
As there are some big Origami changes coming next week it makes sense to upgrade these components now because they'll block the more straightforward upgrades next week.
As part of updating o-forms I realised the way o-forms was being included (declaratively, with the expectation that the consuming client will include all the component sass) is likely to lead to version conflicts that nobody notices. 
To address this, I have brought the code into the component implicitly, and am only using the necessary styles for the rss field. 
I have tested this in next-article and it works as I would expect. I don't anticipate any issues with the app as these are pretty simple changes, but if someone with the apps spun up could help me …
> Update o-forms and o-buttons in podcast launcher

- components/x-teaser/__fixtures__/article-with-data-image.json
- components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/__tests__/snapshots.test.js
- components/x-teaser/readme.md
- components/x-teaser/src/Image.jsx
To improve speed of loading images in the app, we'd like to switch to `blob:` URLs generated via `URL.createObjectURL()`. At the moment x-teaser doesn't recognise these and so tries to load them via the image service; this is a simple change just adding them to the existing exception that exists for `data:` URLs.
I've added a test for the `data:` uri functionality just to ensure that wasn't broken - thought it was superfluous to add a similar snapshot for a `blob:` url but happy to do so if you'd like...
> Modify x-teaser image to support blob: URLs for images without trying to pass them to the image service

- components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/readme.md
- components/x-teaser/src/Video.jsx
Adds a `data-o-video-show-guidance` data-attribute to the Video.jsx template which defaults to `true`. 
This will allow us to disable the 'No captions available' guidance for videos which use x-teaser. We want to remove this guidance  for videos on the Front Page as tests have shown that it decreases engagement; [discussion in this trello ticket](https://trello.com/c/qSiuMpf4/110-remove-subtitles-info-from-video-promo-on-ft-homepage). 
Related PR in o-video to support the new attribute: https://github.com/Financial-Times/o-video/pull/149
Related PR to implement this change in next-front-page: https://github.com/Financial-Times/next-front-page/pull/2208
> add a showGuidance data-attribute to the Video.jsx template

- components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/src/Headshot.jsx
- components/x-teaser/src/concerns/image-service.js
- package.json
small teaser images with text look blurry on retina-quality screens:
this increases the size of the image, but reduces the quality. in testing this increases the size of the image, but by an insignificant amount (<5%).
i'm not using `srcset`, because it's my intuition that the size increases from including every image URL twice on a page would offset the size reduction from not loading the larger images on every client, and increasing the size of a (probably lazy-loaded) subresource will have less of an impact than increasing the size of the initial page.
> Output 2x images at lower lossy quality

- components/x-teaser/src/Headshot.jsx
- components/x-teaser/src/concerns/image-service.js
The global `URL` is only available in node v10
> Revert "refactor image service helper to use URL constructor"

- __tests__/snapshots.test.js
- components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/readme.md
- components/x-teaser/src/Video.jsx
This reapplies @pixelandpage's work to fix video subtitles to a new branch. The `pre-origami-cascade` branch was created from `v1.0.0-beta.21`, and new beta releases should be created from here.
There's definitely some stuff that's slightly wrong about this PR, mostly whitespace, which I'll look into now. I'm going to need help to get this merged and released in a way that doesn't break things.
> Add a disable guidance attribute to videos

- components/x-teaser-timeline/__tests__/lib/transform.test.js
- components/x-teaser-timeline/src/TeaserTimeline.jsx
- components/x-teaser-timeline/src/lib/date.js
- components/x-teaser-timeline/src/lib/transform.js
This PR does not change behaviour or appearance, simply a small refactor in preparation for fixing this bug: https://trello.com/c/tTPiw9x1/3976-topic-bubbles-fix-latest-news-problem-on-stream-pages
It collects together the presentation logic in teaser-timeline into a single entry point `buildModel`, and puts tests around that function, with the aim that `buildModel` can then be refactored safely without changing its behaviour.
> Extract logic from x-teaser-timeline and add tests

- CODEOWNERS
In the durable teams world, the following components are known to be owned by content discovery:
- x-teaser
- x-teaser-timeline
Setting codeowners will direct PR reviews to content disco, which is a good start for ownership.
Other components, such as x-follow-button, are TBC.
> Specify components owned by content disco

- __tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser-timeline/__tests__/__snapshots__/TeaserTimeline.test.jsx.snap
- components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/src/Image.jsx
The change will fix an issue with opening an article when an image isn't available.
The article would not load if a user clicks on an image that isn't available. 
- the fix is very small - we only change the order of a Link and Image components in order to include the ImageComponent inside Link - which fixes the issue.
> Fix article load issue when image is unavailable

- .circleci/config.yml
Gatsby has made a breaking change in a minor version so we need to update to avoid the build breaking.
https://github.com/gatsbyjs/gatsby/pull/22400#issuecomment-627911322
If this is your first `x-dash` pull request please familiarise yourself with the [contribution guide](https://github.com/Financial-Times/x-dash/blob/master/contribution.md) before submitting.
I have ran this Node.js version locally and ran the various npm scripts and they succeed, so I think we may be OK to upgrade without any changes.
Closes https://github.com/Financial-Times/x-dash/pull/442
> Update CircleCi Node.js version to 10.13

- components/x-podcast-launchers/package.json
It's not clear why this has started failing but perhaps since these packages are built in parallel there was a race condition that we were not aware of.
Hopefully by adding node-sass as a dependency to this package, which matches x-gift-article and x-follow-button, we'll resolve this issue and master will not fail.
> Ensure x-podcast-launchers has node-sass dependency.

- .circleci/config.yml
Sorry about the noise with these pull requests.
The master build is currently failing as node-sass binary has been built for Node.js version 8.
The new environment is Node.js version 10, so my assumption is that the dependency cache needs updating which will prompt CircleCi to build the correct node-sass binary.
As noted by @andygout we should be moving towards Dart sass in the future which does not require native binaries but for now I'm aiming to get master passing.
> Fix circleci dependency caching

- components/x-teaser/readme.md
- docs/guides/migrating-to-x-teaser.md
Removes references to `n-image` from the `x-dash` documentation as we are in the process of deprecating this module.
> Remove references to n-image in x-dash docs

- components/x-privacy-manager/src/__tests__/privacy-manager.test.jsx
- components/x-privacy-manager/src/privacy-manager.jsx
- components/x-privacy-manager/src/types.d.ts
This PR extends and enhances the typings for the component and is the submission referred to in the conversation in https://github.com/Financial-Times/x-dash/pull/460 about providing stronger guidance re required/optional props
Although X-Dash does not support TS itself, the combination of JSDoc comments and VSCode Intellisense can greatly add to the ease of development and consistency of documentation
> X privacy manager enhanced types

- components/x-privacy-manager/src/__tests__/privacy-manager.test.jsx
- components/x-privacy-manager/src/privacy-manager.jsx
This adds `error` as the first parameter to consent callbacks in `x-privacy-manager` in the style of Node.js callbacks.
> Add error arg to consent callbacks in x-privacy-manager

- components/x-privacy-manager/src/privacy-manager.jsx
- components/x-privacy-manager/src/types.d.ts
- components/x-privacy-manager/storybook/data.js
- components/x-privacy-manager/storybook/story-save-failed.js
Running registered callbacks on both success and error responses from the server requires a change to the typings to accept an error message as the first argument (following the Node convention)
> Update typings to reflect revised callback signatures

- components/x-privacy-manager/src/privacy-manager.jsx
- components/x-privacy-manager/storybook/data.js
- components/x-privacy-manager/storybook/story-consent-accepted.js
- components/x-privacy-manager/storybook/story-consent-blocked.js
- components/x-privacy-manager/storybook/story-consent-indeterminate.js
- components/x-privacy-manager/storybook/story-save-failed.js
Updates in this PR:
1. Supply the expected shape & content for `consentProxyEndpoints`
1. Make `fetchMock` calls configurable to allow simulating a failed response
Duplicated logic on server response was removed
> Update stories and remove duplicated logic on server response

- changelog.md
In accordance with the [Release Guidelines](https://github.com/Financial-Times/x-dash/blob/master/docs/components/release-guidelines.md), this PR updates `changelog.md` to include **v1.0.6**: a patch release that includes unreleased commits merged to `master` branch since the last release (v1.0.5, released 25 Feb 2020).
In addition to the commits added to `changelog.md` in this PR, there were others that did as detailed below, but which are not of any real value to consumers of `x-dash` and so were omitted:
- Update `CODEOWNERS`.
- Remove references to `n-image` in `x-dash` docs.
- Merge and reversion of new component `x-privacy-manager`, which has now been fully tested and will be merged soon.
> Version 1.0.6

- components/x-privacy-manager/readme.md
The README contained too much generic information about x-dash itself relative to practical instructions on how to use the component. 
This PR removes material available elsewhere and adds more specific insights for developers of consuming apps on how to interact with it.
> Improve README with instructions on registering callacks

- components/x-privacy-manager/package.json
As the first production release of the component, the PR updates the version to 1.0.0
> Bumps x-privacy-manager version to 1.0.0

- __tests__/__snapshots__/snapshots.test.js.snap
- components/x-gift-article/src/GiftArticle.scss
- components/x-gift-article/src/Url.jsx
Fixes issue rasied in DAC Q2 2020 audit.
Gift article link input has no associated label or aria-label property.
For more detail see: https://financialtimes.atlassian.net/browse/ACC-433
Adds aria-label to input as this seems the most aproprate fix due to the context of it being in a 'gift article' modal box.
Should be treated as a patch release.
> ACC-433 gift article form field label

- components/x-gift-article/src/Buttons.jsx
This is a minor touch up to improve accessibility and make it clear what the user is copying.
> ACC-434 Added aria to copy button

- __tests__/__snapshots__/snapshots.test.js.snap
- components/x-gift-article/bower.json
- components/x-gift-article/src/GiftArticle.scss
- components/x-gift-article/src/RadioButtonsSection.jsx
Groups radio button inputs as a multiple form input for Assistive technology(AT).. 
Addresses the DAC issue raised in the Q2 audit see: https://financialtimes.atlassian.net/browse/ACC-432
DAC recommendation was to group in fieldset and ledgend but the grouping has been applied using role on the containing element and aria-labelledby properties for reasons described in o-forms accessibility docs: 
https://github.com/Financial-Times/o-forms/blob/master/ACCESSIBILITY.md#multiple-inputs
> ACC-432 radio buttons group reference

- components/x-privacy-manager/package.json
- components/x-privacy-manager/src/privacy-manager.jsx
- components/x-privacy-manager/src/privacy-manager.scss
- components/x-privacy-manager/src/radio-btn.jsx
- components/x-privacy-manager/src/radio-btn.scss
- components/x-privacy-manager/src/types.d.ts
- components/x-privacy-manager/storybook/data.js
- components/x-privacy-manager/storybook/knobs.js
This PR rolls up the following feature additions and bug fixes:
- Bugfix: fastclick requiring double clicks to select an option
- [ADSDEV-543](https://financialtimes.atlassian.net/browse/ADSDEV-543): Encourage logged-out users wishing to update their DNS preferences to sign in
- [ADSDEV-431](https://financialtimes.atlassian.net/browse/ADSDEV-431): Add tracking attributes
- [ADSDEV-527](https://financialtimes.atlassian.net/browse/ADSDEV-527): Update legal copy
> x-privacy-manager v1.1.0

- components/x-privacy-manager/readme.md
- components/x-privacy-manager/src/__tests__/privacy-manager.test.jsx
- components/x-privacy-manager/src/privacy-manager.jsx
- components/x-privacy-manager/src/radio-btn.jsx
- components/x-privacy-manager/src/types.d.ts
Updates `x-privacy-manager`
Adds an optional `cookieDomain` prop that allows consuming apps to override the domain of the consent cookie being set with the successful response from Consent API. When provided, the `cookieDomain` prop is attached to the payload being sent over to Consent Proxy and overrides the default ".ft.com" here https://github.com/Financial-Times/next-consent-proxy/blob/master/src/controllers/set-consent-record-cookie.ts#L58
Background:
This component is used on specialist titles (e.g. https://cookies.ftadviser.com/preferences/privacy-ccpa?referrer=www.ftadviser.com&cookieDomain=.ftadviser.com&legislation=ccpa ) where the consent cookie from Consent API needs to be set to the appropriate domain for the title. 
[This PR in …
> Add an optional cookieDomain to PrivacyManager

- components/x-live-blog-post/src/ShareButtons.jsx
- components/x-live-blog-post/src/__tests__/ShareButtons.test.jsx
The `x-live-blog-post` share URLs are not working in `next-article` because at some point they are being double encoded. As a result, users who click on the LinkedIn share link on a live blog post are being sent to an error page:
[Content Innovation Ticket](https://financialtimes.atlassian.net/browse/CI-261)
> CI-261 Remove `&amp;` from share URLs

- components/x-live-blog-post/src/LiveBlogPost.scss
Contrast on the timestamp was too low, making it inaccessible. Josh W. has approved the use of the slightly darker shade. To be honest, both colours looks the same to me 😂 
**Before:**
**After:**
> CI-287 Improve timestamp colour contrast

- components/x-live-blog-post/src/Timestamp.jsx
- components/x-live-blog-post/src/__tests__/Timestamp.test.jsx
The latest version allows us to render a date multiple times within the
same `o-date` component by including multiple `data-o-date-printer`
elements.
FYI, there is no visual change to the timestamp.
See https://github.com/Financial-Times/o-date/releases/tag/v4.1.0.
> CI-288 Update timestamp to use latest version of `o-date`

- components/x-teaser/__fixtures__/top-story.json
- components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/readme.md
- components/x-teaser/src/Container.jsx
- components/x-teaser/storybook/article.js
- components/x-teaser/storybook/content-package.js
- components/x-teaser/storybook/knobs.js
- components/x-teaser/storybook/opinion.js
- components/x-teaser/storybook/package-item.js
- components/x-teaser/storybook/podcast.js
- components/x-teaser/storybook/promoted.js
- components/x-teaser/storybook/top-story.js
- components/x-teaser/storybook/video.js
This introduces another attribute to the teaser: data-trackable
There are data-trackable for various bits within the teaser (e.g. link type) however we need a data-trackable for the teaser as a whole. One example is to add details where the teaser is placed on the frontpage:
- `data-trackable="slice:hero-slice-1;slicePos:1;layout:standaloneimage;listPos:1"` (first top story)
- `data-trackable="slice:freeform-twocolumns;slicePos:5;layout:standaloneimage;listPos:14"` (last top story)
See https://github.com/Financial-Times/next-front-page/pull/2392 for the code there to add the above tracking. That PR would follow this PR (& release).
So, in short, this PR simply allows users of `x-teaser` to specify, optionally, a tracking value for the teaser.
> Allow users to specify the data-trackable attribute for the teaser

- components/x-live-blog-post/src/LiveBlogPost.jsx
- components/x-live-blog-post/src/__tests__/LiveBlogPost.test.jsx
Only render the H1 element if a title property exists.
Some old blogs posts don't have titles and this will generate empty h1 tags which will fail accessibility checks
> Wrap x-live-blog-post title in conditional

- components/x-live-blog-wrapper/readme.md
- components/x-live-blog-wrapper/src/LiveBlogWrapper.jsx
- components/x-live-blog-wrapper/src/LiveEventListener.js
There are two major updates to use this component at the client side:
We need to render a property named `data-x-live-blog-wrapper-id` in the main element. This is now used to identify the element at the client side for live updates.
Previously we used `data-x-dash-id` for this purpose, but that property is only rendered when using this component with server side rendering.
With server side rendering and hydrating at the client side, component actions can be triggered by dispatching a custom event named `x-interaction.trigger-actions`. This method can't be used with client side rendering. Therefore we need pass the `actions` object to `listenToLiveEvents` function as an argument.
`actions` object can be gathered by passing a callback function to the component in a property named …
> Updates to use this component at the client side

- components/x-live-blog-post/src/LiveBlogPost.scss
In order for the `Element.clientHeight` property of the `x-live-blog-post` component's main container element to correctly reflect the height of all child elements, including their margins, we need to ensure that the container fully wraps all elements.
Related pull request: https://github.com/Financial-Times/next-article/pull/3929
> Fix height of x-live-blog-post component

- components/x-live-blog-post/src/LiveBlogPost.jsx
- components/x-live-blog-post/src/__tests__/LiveBlogPost.test.jsx
Add a `data-component="x-live-blog-post"` to each instance of the
component which can then be used by client side to target the component.
An example for this component is that it adds share buttons but the
parent application is responsible for initilising the o-share. This
allows us to query every post and initilise o-share for that instance.
> Add a data-x-component attribute to live blog post

- components/x-live-blog-post/readme.md
- components/x-live-blog-post/src/LiveBlogPost.jsx
- components/x-live-blog-post/src/__tests__/LiveBlogPost.test.jsx
- components/x-live-blog-post/storybook/index.jsx
This component was originally produced whilst we were receiving data
from the wordpress cms and we didn't have a schema for the Spark CMS
yet.
Whilst we are running both systems side by side I have added some new
arguments that will in the longer term replace some of the old
arguments.
I have made this change within the x-dash component to avoid having to
map property names in the systems that use this component.
This allows us to release this change as a minor release rather than a
major breaking change and then release a major when we remove these
arguments in the future.
**Argument mapping**
New argument      | Old argument 
------------------|---------------
`id`                        | `postId`
`bodyHTML`        | `content`
`publishedDate ` | `publishedTimestamp`
> Update x-live-blog-post arguments

- packages/x-test-utils/package.json
This PR https://github.com/Financial-Times/x-dash/pull/528 is proposing to remove the `npx snyk monitor --org=customer-products --project-name=Financial-Times/x-dash` command in the CI process until we can resolve the issue (for which we have a support ticket raised with Snyk).
If merged, it might not be a bad idea to do so where the repo is in a state that has no outstanding Snyk issues - there is currently one for which Snyk has recommended upgraded `jest-enzyme` to v7.
The breaking change in v7 of `jest-enzyme` (detailed in its [Releases](https://github.com/FormidableLabs/enzyme-matchers/releases) page) was renaming `toHaveTagName` to `toHaveDisplayName`, but this repo does not include `toHaveTagName` and so is unaffected.
> Upgrade jest-enzyme dependency ^6.0.4 -> ^7.0.2

- .circleci/config.yml
This task currently fails for an unknown reason. We have created a support ticket in snyk support and waiting for a response.
Meanwhile, to unblock release of components, we remove this task from the publish step temporarily.
Link to the failing build: https://app.circleci.com/pipelines/github/Financial-Times/x-dash/2785/workflows/32e5bc8f-6e0e-4f9c-bfb6-75a257784bdc/jobs/5806
Link to the Slack conversation with snyk support: https://financialtimes.slack.com/archives/CFZKWHHM0/p1600419469002800
> Removes snyk monitor task from CircleCI publish step

- components/x-live-blog-post/src/LiveBlogPost.scss
- components/x-live-blog-wrapper/storybook/index.jsx
The bottom padding for the live blog post used to rely on sharing buttons to be visible. In the ft-app we don't display the share buttons in this component and the padding doesn't look right.
This fixes the bottom padding regardless of displaying or hiding the share buttons.
**Before:**
**After:**
> Fix live-blog-post padding

- .circleci/config.yml
- https://financialtimes.atlassian.net/browse/CPP-297
- This reverts commit `71b5bd6e480abe5210939262dc38461a963354a3` and add the `snyk` step back into the CI job.
> Revert "Removes snyk monitor task from CircleCI publish step"

- components/x-live-blog-post/src/LiveBlogPost.jsx
- components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap
Fixes live blog post body styles in the FT App.
**Before:**
**After:**
**Before:**
**After:**
> Add n-content-body class to live blog post body

- .circleci/config.yml
Snyk job fails with a generic error. There is no way of debugging this.
Currently the live blogs work is blocked by this.
> Remove snyk from publish step in CircleCI temporarily

- components/x-live-blog-post/src/LiveBlogPost.jsx
We add `article--body` class to the wrapper div of live blog posts to fix the rendering of blockquotes in the FT App.
Before:
After:
> Fix live blog post blockquote styling on FT App

- components/x-live-blog-wrapper/src/LiveBlogWrapper.jsx
To initialise Origami components on the live blog posts, FT app needs a reference to the DOM element that wraps the posts.
We add a property named `liveBlogWrapperElementRef` to x-live-blog-wrapper for this purpose.
This will be used in the ft-app like the following:
```javascript
// live blog component in the ft-app
import { createRef } from 'preact';
constructor () {
this.liveBlogRef = createRef();
}
render () {
return (<LiveBlogWrapper {...props} liveBlogWrapperElementRef={this.liveBlogRef} />)
}
componentDidMount () {
const dateElements = this.liveBlogRef.current.querySelectorAll('query-for-o-date-elements');
// init oDate for each date element
}
```
> Forward the ref callback to the main element that wraps live blogs

- .circleci/config.yml
Adding this flag as suggested above has fixed the same problem in [`next-fastly-to-graphite`](https://github.com/Financial-Times/next-fastly-to-graphite) - see: https://app.circleci.com/pipelines/github/Financial-Times/next-fastly-to-graphite/386/workflows/d304e13f-4ec6-4712-872d-7287532b58f1/jobs/3328.
> Revise npx snyk monitor CircleCI config command

- components/x-live-blog-post/package.json
The [main branch CI workflow](https://app.circleci.com/pipelines/github/Financial-Times/x-dash/2991/workflows/0c38773c-6007-4b2c-bcd7-5a8c863c0b74/jobs/6201) is currently failing at the build stage owing to:
> ✖ Task failed in components/x-live-blog-post
> ✖ You need to install one of the following packages: "node-sass", "sass" in order to process SASS files
The `x-live-blog-post` component does indeed contain `.scss` files (`./src/LiveBlogPost.scss`).
All other components that include `.scss` files include either `node-sass` or `sass` as a dev dependency, but `x-live-blog-post` does include either.
This PR adds `node-sass` as a dev dependency of the `x-live-blog-post` component.
Until now the build has been passing without this dev dependency. Ostensibly, it only started failing until …
> Add x-live-blog-post node-sass dev dependency

- .circleci/config.yml
The [main branch CI workflow](https://app.circleci.com/pipelines/github/Financial-Times/x-dash/3002/workflows/614a78dc-7c0a-4759-8698-2eba4ff7304c/jobs/6205) is currently failing at build stage owing to:
> ERR! Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x
> ERR! This usually happens because your environment has changed since running `npm install`.
> ERR! Run `npm rebuild node-sass` to download the binding for your current environment.
This issue has historically been fixed by bumping the cache keys, which is done in this PR.
---
If this is your first `x-dash` pull request please familiarise yourself with the [contribution guide](https://github.com/Financial-Times/x-dash/blob/master/contribution.md) before submitting.
- Add the `Component` …
> Bump CircleCI cache keys

- components/x-live-blog-wrapper/src/LiveEventListener.js
I am in the process of rendering live updates to FT.com. While doing this, I came across a couple of bugs which prevented us from triggering the actions to create, update and delete a post. I broke up the fixes into separate commits and explained the "why" in the commit message. But long story short, we were using the wrong property name for accessing the post ID and we weren't bubbling an event to the parent when we should have been.
We are now able to render a live update to FT.com:
> Fix bugs with triggering live blog wrapper actions

- .circleci/config.yml
A Snyk error is preventing me from releasing a [new version of `x-dash`](https://github.com/Financial-Times/x-dash/pull/551). We thought this error was resolved but it looks not to be the case. Andy has reported the issue to Snyk again and we are waiting on them. Because we don't know if there will be a fix soon, I am going to remove the Snyk command, publish a new release and then re-add the Snyk command.
See more info here: https://financialtimes.slack.com/archives/C3TJ6KXEU/p1605111138223300
> Remove Snyk command from CircleCI publish step

- components/x-live-blog-wrapper/src/LiveBlogWrapper.jsx
- components/x-live-blog-wrapper/src/__tests__/LiveBlogWrapper.test.jsx
I forgot to update how we access post ID in this commit: https://github.com/Financial-Times/x-dash/pull/551/commits/be96eb0e44b6b0ef70a3112716fc768b302daf36.
Essentially, `next-live-blog-trigger` renamed the post ID property from `id` to `postId` which means when we receive the event, we need to access the post id as `updated.postId`. 
I tested this out in `next-article` and the most recent blog post was successfully deleted.
Before
After
> CI-392 Fix bug with accessing post ID

- .circleci/config.yml
A Snyk error is preventing me from releasing a new version of `x-dash`.
Snyk is aware of the issue and Andy is working with them to debug.
Because we don't know if there will be a fix soon, I am going to remove
the Snyk command, publish a new release and then re-add the Snyk
command.
> Remove failing Snyk CircleCI command

- .circleci/config.yml
This Snyk command is not currently doing anything (in either of its two appearances). I learned from the Snyk Support Team that the `snyk monitor` command only looks at `dependencies`, not `devDependencies`. The `package.json` in the root dir of this repo only has `devDependencies` and so the command fails because it cannot find any `dependencies` to examine.
So there is no net change from removing this command, other than CI builds will no longer fail owing to this Snyk-related failure.
I am currently corresponding with the Snyk Support Team to get a command that will monitor all the `package.json` files in subdirectories (which would be an increase in scope of what the existing code sought to achieve), but ignore the one in the root dir given the problems it is causing us, as well as …
> Remove Snyk monitor command from CircleCI config

- .storybook/webpack.config.js
- package.json
SB wouldn't build for without adding react-dom and providing a default babel config object.
> Additions required to run SB with a fresh install

- components/x-teaser/src/concerns/image-service.js
When attempting to view `x-teaser` in Storybook, I came across a `TypeError: URL is not a constructor` on the page and I see the same error when running `next-front-page` locally. When I remove this line of code, the error disappears and I'm able to view the `x-teaser` stories.
**Storybook**
**local.ft.com:5050**
This line of code was added 2 months ago to restore compatibility with Node v6, see https://github.com/Financial-Times/x-dash/commit/24984503bb33142d544eaeb0fba4751310c21d4b.
Not sure if removing this line of code is the best fix so feedback would be appreciated!
> Fix URL error

- components/x-live-blog-wrapper/src/LiveBlogWrapper.jsx
- components/x-live-blog-wrapper/src/__tests__/LiveBlogWrapper.test.jsx
Without this the component wouldn't work with x-interaction when the code is transpiled for production.
It was working with development code I believe because it was relying in on the standard Javascript name property of the function.
When the code was transpiled for production the functions were minified the function names were changed or made anonymous.
By hardcoding this displayName as a string it allows x-interaction to register the component and reference it by name.
> Give the x-live-blog-wrapper component a displayName - CI-423

- components/x-live-blog-wrapper/readme.md
- components/x-live-blog-wrapper/src/LiveEventListener.js
Make it easier for us to test the component locally.
I tested this locally in `next-article` by building the component locally and configuring the plugin as is documented.
> Allow `next-live-event-api` endpoint URL to be overriden

- components/x-gift-article/src/GiftArticle.scss
- components/x-gift-article/src/MobileShareButtons.scss
- components/x-gift-article/storybook/index.jsx
- components/x-podcast-launchers/storybook/index.jsx
- components/x-styling-demo/storybook/index.jsx
- components/x-teaser-timeline/bower.json
- components/x-teaser-timeline/src/TeaserTimeline.scss
- components/x-teaser-timeline/storybook/index.jsx
- components/x-teaser/storybook/index.jsx
[Ticket CPP-351](https://financialtimes.atlassian.net/browse/CPP-351)
When Webpack rebuilds on changes it checks files ending with `.jsx`, since some Storybook stories were importing components from `/dist` files ending in `.cjs`, these were not getting rebuilt. 
Changing Storybook so that it imports the `.jsx` components instead, made some build errors get thrown, which were fixed by upgrading `o-typography`, `o-grid`, `o-colors`. The changes in `TeaserTimeline.scss` are related to these version upgrades.
> CPP-351 Editing x-dash components does not update Storybook

- components/x-live-blog-post/src/LiveBlogPost.jsx
- components/x-live-blog-post/src/__tests__/LiveBlogPost.test.jsx
- components/x-live-blog-post/storybook/index.jsx
The data we get from Spark and UPP for breaking news is `standout.breakingNews`
This change uses that property to render the breaking news label.
For now it also still uses the `isBreakingNews` property that is used for wordpress data.
If this is your first `x-dash` pull request please familiarise yourself with the [contribution guide](https://github.com/Financial-Times/x-dash/blob/master/contribution.md) before submitting.
> Update breaking news label based on Spark data

- .circleci/config.yml
- private/scripts/gh-pages
Reverts Financial-Times/x-dash#571
[Build fails with permission denied](https://app.circleci.com/pipelines/github/Financial-Times/x-dash/3299/workflows/e4981465-7de0-4607-b179-6e485d00472e/jobs/6631), my guess is that it has something to do with github configuration in the script
> Revert "CPP-344 use ci helper to publish to github pages"

- components/x-live-blog-post/src/LiveBlogPost.jsx
- components/x-live-blog-post/src/LiveBlogPost.scss
- components/x-live-blog-post/src/__tests__/LiveBlogPost.test.jsx
- components/x-live-blog-post/storybook/index.jsx
In Wordpress, the post author was part of the main body HTML. With Spark, we now have a `byline` field which is used to enter a post author. 
The `byline` property is passed down from `next-article` and `ft-app` to `x-live-blog-wrapper`. Then `x-live-blog-wrapper` passes it down to `x-live-blog-post` which is responsible for rendering the post author.
**FT.com**
I had to do some work in `next-article` to make these changes work, see https://github.com/Financial-Times/next-article/pull/4101.
**App**
I had to do some work in `ft-app-api` to make these changes work, see https://github.com/Financial-Times/ft-app-api/pull/295.
> CI-422 Render live blog post author

- components/x-teaser/__fixtures__/article-with-missing-image-url.json
- components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/__tests__/snapshots.test.js
- components/x-teaser/src/Image.jsx
Check for existence of `image` as soon as image teaser function starts so that the line
```js
const useImageService = !(image.url.startsWith('data:') || image.url.startsWith('blob:'))
```
doesn't error if `image` is undefined. This has happened twice on the homepage when a gif has been used as the main image. when this errors on the home page the whole home page returns a 500.
Now when image is null stories render without images rather than the whole page going down:
> Check for existence of image as soon as image teaser function starts

- components/x-live-blog-wrapper/readme.md
- components/x-live-blog-wrapper/src/LiveBlogWrapper.jsx
- components/x-live-blog-wrapper/src/LiveEventListener.js
- components/x-live-blog-wrapper/src/__tests__/LiveBlogWrapper.test.jsx
- components/x-live-blog-wrapper/src/__tests__/LiveEventListener.test.js
- components/x-live-blog-wrapper/src/__tests__/dispatchEvent.test.js
- components/x-live-blog-wrapper/src/__tests__/normalisePost.test.js
- components/x-live-blog-wrapper/src/dispatchEvent.js
- components/x-live-blog-wrapper/src/normalisePost.js
If updates that come from the pipeline include duplicate we want to make sure our users only see one post.
We can do this by checking for the existence of a post with the same ID.
We also need to move our external events so they fire only when there's been an update.
I have also written tests for some of the existing logic in this component to try to increase the confidence I have with changing it.
Best viewed commit by commit
> CI-479: Only insert posts if they do not already exist, and remove update + delete events

- components/x-interaction/readme.md
- components/x-interaction/src/Hydrate.jsx
- components/x-interaction/src/Interaction.jsx
- components/x-interaction/src/InteractionSSR.jsx
- components/x-interaction/src/concerns/get-component-name.js
- components/x-interaction/src/concerns/register-component.js
- components/x-interaction/src/concerns/serialiser.js
- components/x-interaction/src/concerns/wrap-component-name.js
- components/x-live-blog-wrapper/src/LiveBlogWrapper.jsx
[Ticket CPP-419](https://financialtimes.atlassian.net/browse/CPP-419)
From the ticket description: 
> x-interaction allows you to serialise component data for server-rendered components, and hydrate those components on the client side to enable actions with the client-side version of the component. registering components happens implicitly within x-interaction, and relies on heuristics to determine the component name. these must work the same on the client and server for the component to hydrate properly, which is unreliable, and is more likely to break in production environments than development.
This PR makes x-interaction export an explicit register function instead of implicitly registering. It also sets checks in both server (Serialiser) and client (Hydrate) code to ensure that all …
> CPP-419 x-interaction component registration

- contribution.md
The release guidelines were extracted from `contribution.md` into their own file.
This PR updates the link in `contribution.md` to point to that separate file.
> Update Releasing/Versioning link in contribution.md

- components/x-interaction/src/concerns/register-component.js
- components/x-interaction/src/concerns/wrap-component-name.js
- components/x-live-blog-wrapper/src/LiveBlogWrapper.jsx
if the original component is registered, when we try to hydrate it it'll render the markup but it doesn't have the actions. previously, if the wrapper component was registered, the serialiser would complain because it's trying to get the name of the component from the original component, which doesn't know it.
i'm not set up to test live blogs locally, so @GlynnPhillips i'd really appreciate if you could kick the tyres :)
> CPP-464 register wrapper components and allow accessing wrapper components from original component

- components/x-gift-article/readme.md
- components/x-gift-article/src/CopyConfirmation.jsx
- components/x-gift-article/src/Form.jsx
- components/x-gift-article/src/GiftArticle.jsx
- components/x-gift-article/src/GiftArticle.scss
- components/x-gift-article/src/Message.jsx
- components/x-gift-article/src/RadioButtonsSection.jsx
- components/x-gift-article/src/Title.jsx
- components/x-gift-article/src/UrlSection.jsx
- components/x-gift-article/src/lib/updaters.js
This PR is https://github.com/Financial-Times/x-dash/pull/578 wrapped in a flag so that we can run an AB test. 
This PR is one of many steps to get the AB test rolled out:
> ACC-749 x-gift-article improvements wrapped in a flag

- components/x-gift-article/src/Title.jsx
Somehow the stray semicolon and the lack of `return` snuck past everyone and made for somewhat unpleasant gifting experience. It meant that the Title was not displayed at all. 
With other work taking priority the work on gifting AB test needs to be paused, but with this patch x-gift-article should work as it previously did whist retaining the prep work for the gifting AB
> ACC-749 fix: removed a stray semicolon and wrapped the div inside a return

- components/x-privacy-manager/src/actions.js
- packages/x-babel-config/jest.js
- packages/x-rollup/src/rollup-config.js
Last week I found that a clean install of x-dash was failing to compile any of the components: running `make build` would error with the following message:
```
✖ [BABEL] <path-to-repo>/components/x-teaser/src/Teaser.jsx: @babel/helper-compilation-targets: '[object Object]' is not a valid browserslist query (While processing: "<path-to-repo>/packages/x-babel-config/node_modules/@babel/preset-env/lib/index.js")
```
Today @nickcolley reported having the same issue, so this PR is submitted as the quickest way to get compiling.
I investigated making a fuller update to the rollup dependencies (since the current versions have moved under the @rollup namespace) but had issues with emitting the `babelHelpers` in a form that consuming apps (such as `next-control-centre`) could pick up
> Minimal fix: refactor targets properties alone

- components/x-live-blog-post/src/LiveBlogPost.scss
This was preventing us using `scroll-margin` to make the linking to the post via anchor better.
It was previously added to [allow for better calculations of the height of a post for scroll adjustments](https://github.com/Financial-Times/x-dash/commit/c90b2a459b5cc8a8a07a85faf1726ad358187444), but we no longer do this so we can remove it.
> CI-564: Remove overflow: auto from live blog post

- components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/src/Headshot.jsx
Currently on site headshots on the front page are not tinted blue, which they should be:
This fixes them so the tint is correctly applied:
The headshot file creates an options variable **string** containing the tint values which is later passed into an `imageService` function used to construct the URL to the Origami image service:
```js
const options = `tint=${headshotTint || DEFAULT_TINT}`
...
src={imageService(headshot, ImageSizes.Headshot, options)}
```
[The `imageService` function](https://github.com/Financial-Times/x-dash/blob/main/components/x-teaser/src/concerns/image-service.js) expects an **object** (which is spread into a base object to create the URL) and so incorrectly handles the incoming string and produces a garbage query param on the constructed URL:
```js
imageSrc.search …
```
> NOPS-722 Fix blue headshots

- components/x-live-blog-post/readme.md
We added functionality to render a byline here:
https://github.com/Financial-Times/x-dash/commit/15eddd1741e87ba405acd9f73958a0eaa161c92a
This adds the documentation for that new property.
> Update x-live-blog-post byline documentation

- components/x-privacy-manager/src/__tests__/helpers.js
- components/x-privacy-manager/src/actions.js
This PR adds a `setConsentCookie` property to the payload to trigger the setting of the `FTConsent_GDPR` cookie in the response from the server
> Update payload to ensure that FTConsent_GDPR is set

- components/x-privacy-manager/jsconfig.json
- components/x-privacy-manager/src/__tests__/helpers.js
- components/x-privacy-manager/src/__tests__/messaging.test.jsx
- components/x-privacy-manager/src/__tests__/state.test.jsx
- components/x-privacy-manager/src/actions.js
- components/x-privacy-manager/src/components/form.jsx
- components/x-privacy-manager/src/components/messages.jsx
- components/x-privacy-manager/src/components/radio-btn.jsx
- components/x-privacy-manager/src/privacy-manager.jsx
- components/x-privacy-manager/src/utils.js
- components/x-privacy-manager/storybook/stories/consent-accepted.js
- components/x-privacy-manager/storybook/stories/consent-indeterminate.js
- components/x-privacy-manager/storybook/stories/save-failed.js
- components/x-privacy-manager/typings/x-privacy-manager.d.ts
It has transpired that the Privacy Manager component should send the `setConsentCookie` flag based on  legislation: CCPA users opting in/out of the sale of their data should not have `FTConsent_GDPR` set to true because they should still be shown the cookie banner.
This PR [encapsulates that requirement](https://github.com/Financial-Times/x-dash/pull/596/files#diff-5c14b4096cd7b936e70498295744fa9fa2a6d91df6a92a676892bd6fefd26614R70) so that consuming apps do not need to make any changes
Additionally 
- Tests have been refactored to simplify the mounting a configured instance of the component
- Type definitions have been updated to make reference easier under an `XPrivacyManager` namespace
> Send setConsentCookie only when legislationId is 'gdpr'

- components/x-teaser-timeline/__tests__/lib/transform.test.js
- components/x-teaser-timeline/readme.md
- components/x-teaser-timeline/src/lib/transform.js
This update is a minor patch to enable multiple customSlots to be added to the `x-teaser-timeline` component.
Ideally I'd liked to have make this a new import, but I didn't want to make the change a breaking one. `x-teaser-timeline` can still accept the old style of customSlot (a String and a Number), but now also allows for multiple components.
> handle multiple customSlot components for x-teaser-timeline

- package.json
The 404 error on Storybook started showing up again after the main branch ran the `deploy` task on CircleCI. I have been able to fix it locally by removing the `build-storybook` command, my guess is that it could be because the `storybook-to-ghpages` also runs a command named `build-storybook`.
If it is not that it could be that I am running the `storybook-to-ghpages` command without the `--ci` option locally.
I also removed the unused scripts for the docs.
> Remove unused docs and sb build scripts

- components/x-teaser/src/LiveBlogStatus.jsx
- components/x-teaser/src/RelativeTime.jsx
- components/x-teaser/storybook/index.jsx
* Apps team UX noticed that the App is out of sync with FT.com and has less spacing between the Teaser status dot and the status text (FT.com currently has `5px`). 
* Investigation found that FT.com is using some older versions of `o-teaser` and `o-labels` - `next-front-page` uses `o-teaser "4.1.0-beta.1", "o-labels": "^5.0.0", "@financial-times/x-teaser": "^4.1.3"`, `ft-app` uses `o-teaser": "^5.2.2", o-labels": "^5.1.5", x-teaser": "5.2.0"`
* `o-labels` now (as of `v5.1.5`) only adds `margin-right: 2px` between these two elements. Change introduced [here](https://github.com/Financial-Times/o-labels/commit/cbdfb2a7d78427b691a439704613f3c2a6c34014#diff-369e718fbbdf6907bf9e45dfdf3234cce054c6e399981f0bca5cfa5a2926d1a8).
* Design spec for the status shows `4px` space between the elements:
* …
> AT-4761 Update x-teaser status spacing

- components/x-gift-article/storybook/free-article.js
- components/x-gift-article/storybook/index.jsx
- components/x-gift-article/storybook/native-share.js
- components/x-gift-article/storybook/with-gift-credits.js
- components/x-gift-article/storybook/without-gift-credits.js
Fixes an issue where the gift articles stories in storybook weren't showing how many credits were left.
As per the gift article docs, the `activate` action needs to be called to run the API call (which is mocked by `node-fetch` in this case.) Not exactly sure where the best place to do this would be so I just put it inside its own `actionRef` callback. Maybe this makes sense as we aren't showing the `GiftArticle` component conditionally, instead showing it as soon as it's mounted.
For reference:
- [Description of `actionRef`](https://github.com/Financial-Times/x-dash/tree/09fd985bd97ce907cb297ad586ac9989cee9c296/components/x-gift-article#usage)
- [Description of the `ref` pattern it's based on](https://reactjs.org/docs/refs-and-the-dom.html)
Screenshot of 'With gift credits' story before …
> Fix gift article storybook to call activate action

- packages/x-engine/src/concerns/presets.js
We currently support Fragments in react and hyperons, but not preact ([which did not support Fragments until the latest major version, 10.x](https://preactjs.com/guide/v10/whats-new/#fragments)).
This PR adds support via x-engine for `preact.Fragment`.
I'm unsure how this change should affect versioning. So would very much appreciate input on that.
> feat: Add support for Preact.Fragment in x-engine

- components/x-follow-button/src/styles/mixins/lozenge/_themes.scss
- components/x-follow-button/src/styles/mixins/lozenge/main.scss
When background is dark colour (claret, oxford, teal...), there is not enough contrast between background and focus outline colour.
Colour ratio:
Foreground: #807973
Background: #990F3D
The contrast ratio is: 2:1 (**It should be over 3:1**)
This issue was reported by DAC 2021 summer doc. ([Jira ticket](https://financialtimes.atlassian.net/browse/CON-1096))
To fix this issue, applying white outline instead of grey outline(which is provided by o-nomalise).
📝   I'm going to apply the same change to n-myft-ui follow button css as well ([the PR](https://github.com/Financial-Times/n-myft-ui/pull/446)).
|theme|storybook screenshot|
|---|---|
| standard <br>(grey outline)| ![Screenshot 2021-08-16 at 11 23 42](https://user-images.githubusercontent.com/21194161/129553094-7823e352-05b9-444c-ad7d-31e3 …
> Apply focus outline depends on theme colour

- components/x-teaser/src/Title.jsx
`aria-label` on a span element is not readable by screen readers. This PR adds a new hidden element to help screen readers to read the Premium label.
- [Jira](https://financialtimes.atlassian.net/browse/CON-1123)
> CON-1123 - fix invalid use of aria role on x-teaser

- components/x-teaser/src/Title.jsx
This is a clone of this [other PR](https://github.com/Financial-Times/x-dash/pull/610) to fix an accessibility issue on `x-teaser`.
The reason why it's duplicated is because the current homepage is using an old version of `x-teaser` (`v4.1.3`) and upgrade it to the latest (`v6.2.1`) requires an extra effort that might be useless since the homepage will be replace soon. See [Slack thread](https://financialtimes.slack.com/archives/C3TJ6KXEU/p1630922419003200).
To solve this we are creating a `v4` branch that will be used by `next-front-page`
> fix invalid use of aria role on x-teaser

- components/x-live-blog-post/src/LiveBlogPost.jsx
- components/x-live-blog-post/src/__tests__/LiveBlogPost.test.jsx
This PR is a minor patch to the `LiveBlogPost.jsx` component. 
The current component uses `h1` for the title of each post. This doesn't work very well for subscribers who depend on accessibility tool.
We are changing the title of a post to heading level 2 `h2` so it doesn't cause any confusion with the main header of a live-blog package.
> changed live-blog-post title tag to h2

- components/x-privacy-manager/src/components/radio-btn.scss
- components/x-privacy-manager/src/privacy-manager.scss
See tickets [ADSDEV-897][ADSDEV-897] and [ADSDEV-898][ADSDEV-898].
Fixes an accessibility issue where the focus outline provided failed against the adjacent radio button colour, making it difficult for keyboard users to see that the element has received focus.
The component has been updated to use the colour `teal-100` for the focus outline.
* this is the same outline colour used by default in `o-buttons`.
* it provides a good contrast (>3) compared to the background colour of the button.
[ADSDEV-897]: https://financialtimes.atlassian.net/browse/ADSDEV-897
[ADSDEV-898]: https://financialtimes.atlassian.net/browse/ADSDEV-898
> ADSDEV-898 DAC change outline buttons contrast

- components/x-privacy-manager/src/components/radio-btn.scss
- package.json
`next-control-centre` currently fails DAC requirements:
> When tab navigating the radio, button located on the manage cookies page, the focus outline provided failed against the adjacent radio button colour, making it difficult for keyboard users to see that the element has received focus.
This PR adds an offset to the focus outline making it stand out against its surroundings
> Add outline-offset to ensure that contrast is sufficient

- components/x-privacy-manager/src/privacy-manager.scss
Ticket is [here](https://financialtimes.atlassian.net/jira/software/c/projects/ADSDEV/boards/803?modal=detail&selectedIssue=ADSDEV-898)
Following the example laid out by [this PR](https://github.com/Financial-Times/x-dash/pull/620) by @oliverturner 
We are using `teal-40` to make an offset around the button for when it is in focus. Originally I juggled with a few colours to see if I could find one that had a contrast ratio of 3:1 with both the `paper` and the `teal-40` colour, but there might just not be one.
This keeps the design consistent with Oliver's PR.
Changes are:
- button hover state changed to `teal-40`
- button outline matches hover state to be `teal-40`
- offset for outline of `3px` to make it more obvious
This should result in a contrast of 6.75:1 for the `teal-40` compared …
> outline-offset and background colour change for the form submit save button

- components/x-live-blog-post/readme.md
- components/x-live-blog-post/src/LiveBlogPost.jsx
- components/x-live-blog-post/src/LiveBlogPost.scss
- components/x-live-blog-post/src/ShareButtons.jsx
- components/x-live-blog-post/src/__tests__/LiveBlogPost.test.jsx
- components/x-live-blog-post/storybook/index.jsx
This PR adds a `back to top` link to the bottom of `x-live-blog-post` component. It is a minor feature and with it, a new props have been added to the component. `backToTop`  which can be a function or a string. The aim is to have either `type` passed to achieve same result. The function `type` was added for more fine-grained control of the scrolling with javascript if the consuming component desires that. Pass a string `top` or `#top` to allow the browser handle the scrolling back to top. A string also requires the an element in the `DOM` to have same value as the id attribute.
> added back to top link to liveBlogPost

- components/x-live-blog-post/src/LiveBlogPost.jsx
- components/x-live-blog-post/src/LiveBlogPost.scss
- components/x-live-blog-post/storybook/index.jsx
This is a follow-up PR from https://github.com/Financial-Times/x-dash/pull/621. The back to top button/link is not required on the first post. The initial plan was to let the consumers create overrides in their `css` to achieve this. Because the style names are changed on `build` (CSS modularisation), it becomes harder for the consumer of this component to override the styles as every new version released comes with a new class name.
This PR adds the styling direct to the component and also updates the storybook to reflect this. This CSS class names are also added directly to the styles without any modularisation so consumers can directly select these elements and modify them.
> Hide back-to-top on first Live Blog Post

- components/x-live-blog-post/src/LiveBlogPost.jsx
- components/x-live-blog-post/src/LiveBlogPost.scss
This PR contains a minor change to the structure of the `live-blog-post` component. 
The current component uses `Fragment` from `@financial-times/x-engine` package which doesn't render properly on `ft-app`. I've replaced the Fragment with a `div` and adjusted the styles accordingly.
This specific feature has had 3 releases which is specifically bad for our versions and I take the blame for this. 
I have also tested locally with the local package on both `ft-app` and `next-article` to ensure this issue doesn't show up on the published package.
> removed fragment from live-blog-post component

- components/x-live-blog-post/src/LiveBlogPost.jsx
- components/x-live-blog-post/src/LiveBlogPost.scss
This PR refactors the `x-live-blog-component` and also reintroduced the use of Fragment within the component which was removed before.
The refactor was done mainly because the CSS wasn't BEM compliant.
> refactored the x-live-blog-component.

- .storybook/main.js
- components/x-podcast-launchers/package.json
- components/x-privacy-manager/package.json
- components/x-teaser-timeline/package.json
A few dep bumps...
The App currently installs many (most?) x-dash components, but due to various versions of different components referencing each other, we pull in several components twice at different versions, and x-engine four (!) times. To try to resolve this, I've gone through the various components still on branches and updated them, and then did a review of the components on `main`. I've found a few little things to update:
- x-podcast-launchers was still pulling in a prerelease version of x-follow-button, so I've updated that to use its sibling component from the current version instead.
- x-teaser-timeline was using an old prerelease version of x-article-save-button which was still using x-engine@^1.0.0-beta.7. I've updated this to use a new prerelease which updates to …
> Update cross-component dependencies

- components/x-live-blog-wrapper/readme.md
- components/x-live-blog-wrapper/src/LiveBlogWrapper.jsx
- components/x-live-blog-wrapper/src/lib/post-tracker.js
As part of tracking post visibility. A PostTracker class was introduced to x-dash components. The PostTracker will be used by `x-live-blog-wrapper` component to manage tracking.
On `ft-app` the posts props doesn't get populated on the `componentDidMount` state hook. The setup for PostTracker was done in `componentDidMount` hook and since the posts didn't exist in the DOM, the IntersectionObserver doesn't pick them up.
This PR moves the setUp to the `componentDidUpdate` state hook. Within this hook, we check for the existence of a local PostTracker instance and also changes to the current number of posts in the component. When we have posts and no instance of PostTracker, we create a new PostTracker instance. When we have a PostTracker instance and the number of post changes (specifically …
> moved tracking setup from componentDidMount hook to componentDidUpdate

- .circleci/config.yml
- components/x-follow-button/package.json
- components/x-gift-article/package.json
- components/x-increment/package.json
- components/x-interaction/package.json
- components/x-live-blog-post/package.json
- components/x-live-blog-wrapper/package.json
- components/x-podcast-launchers/package.json
- components/x-privacy-manager/package.json
- components/x-styling-demo/package.json
- components/x-teaser-timeline/package.json
- components/x-teaser/package-lock.json
- components/x-teaser/package.json
- e2e/package.json
- package.json
- packages/x-babel-config/package.json
- packages/x-engine/package.json
- packages/x-handlebars/package.json
- packages/x-node-jsx/package.json
- packages/x-rollup/package.json
- packages/x-test-utils/package.json
We are moving to npm 8 so we are ready to migrate away from bower. There don't appear to be any breaking changes as part of the migration for this repository, so it was as simple as pinning a new npm version with Volta (you can also update your npm globally to test the changes) and making sure CircleCI uses the right npm version too. We have added a `preinstall` script to each package's `package.json` that will make sure that npm 8 is selected when running an install.
> CPP-675 Update to npm 8

- components/x-teaser-timeline/src/lib/transform.js
- components/x-teaser-timeline/typings/x-teaser-timeline.d.ts
JSDoc-style comments aren't reflected in type previews whereas inline comments are
> Improve type comments

- components/x-teaser-timeline/__tests__/lib/transform.test.js
- components/x-teaser-timeline/package.json
- components/x-teaser-timeline/src/TeaserTimeline.jsx
- components/x-teaser-timeline/src/lib/date.js
- components/x-teaser-timeline/src/lib/transform.js
- components/x-teaser-timeline/typings/x-teaser-timeline.d.ts
[ADSDEV-963](https://financialtimes.atlassian.net/browse/ADSDEV-963)
A bug was reported where the X-Teaser-Timeline component attempts to insert ad slots even if the specified position is greater than the number of available teasers.
This PR improves the functionality for inserting the custom slots in between teasers in the teasers timeline, by making sure that the custom slot is inserted only when a suitable position is successfully identified.
This issue mainly impacted the FT App, and the FT App team added a temporary patch in the PR https://github.com/Financial-Times/ft-app/pull/1729
Below I replicated the error by passing a custom slot position value - 15 - greater than the length of the array of items - 10. The X-Teaser-Timeline should skip the insertion of the out-of-bound slot, …
> ADSDEV-963 insert custom slots only if related teaser position is found

- components/x-gift-article/bower.json
- components/x-gift-article/readme.md
- components/x-gift-article/src/Buttons.jsx
- components/x-gift-article/src/Form.jsx
- components/x-gift-article/src/GiftArticle.jsx
- components/x-gift-article/src/GiftArticle.scss
- components/x-gift-article/src/Message.jsx
- components/x-gift-article/src/RadioButtonsSection.jsx
- components/x-gift-article/src/Url.jsx
- components/x-gift-article/src/UrlSection.jsx
- components/x-gift-article/src/lib/constants.js
- components/x-gift-article/src/lib/enterpriseApi.js
- components/x-gift-article/src/lib/tracking.js
- components/x-gift-article/src/lib/updaters.js
- components/x-gift-article/storybook/index.jsx
- components/x-gift-article/storybook/with-enterprise-first-time-user.js
- components/x-gift-article/storybook/with-enterprise-no-credits.js
- components/x-gift-article/storybook/with-enterprise-request-access.js
- components/x-gift-article/storybook/with-enterprise-sharing-link.js
- components/x-gift-article/storybook/with-enterprise.js
- components/x-gift-article/storybook/with-gift-credits.js
This PR adds the enterprise sharing option to x-gift-article.
We are moving enterprise sharing from its own [micro-site](https://enterprise-sharing.ft.com/) to FT.com. This change has been discussed with the accounts team in advance.
* x-gift article will make a request to the enterprise-sharing API and add an new option to the sharing modal if the user is a B2B user:
* Users will be able to compare and choose the best sharing option for their use case.
* There is no breaking changes, If property `enterpriseApiBaseUrl` is not included or enterprise API request fails the modal will just work as usual, without the enterprise option.
I added 4 stories to the x-gift-article storybook, covering the main feature and some edge cases:
| Story | Use Case |
|-------|----------|
| With enterprise …
> ENT-503 Add Enterprise Sharing to Gift Article

- components/x-gift-article/src/GiftArticle.jsx
- components/x-gift-article/src/Message.jsx
- components/x-gift-article/src/lib/enterpriseApi.js
- components/x-gift-article/src/lib/tracking.js
This is a small PR with couple of minor fixes in enterprise sharing, including:
* Remove '90 days' from enterprise sharing confirmation message. This was a mistake in our prototype when the message was copied from the standard gift link. Enterprise sharing links do not expire at the moment da91c04643d5e9d56367c5b1c5f2d0963c997ef8
* Fix error message not appearing if create enterprise link fails due to wrong return value when request to create enterprise sharing link fails 55d345f7c24ebf3ed1ac35ee036864d5ebca3bc9
* Fix inconsistency in tracking and add few data-trackable values (suggested by analytics) b3fe9b69b83bf9290dc26937801ca17393399f4d
* Add tracking when initialising enterprise sharing for better estimation of conversion rates  (suggested by analytics) …
> Update copy and error handling in enterprise sharing x gift article

- components/x-teaser-list/bower.json
this was the only Origami component not on its latest Bower version; but, it's not actually using it, so,
> remove unused o-grid-dependency from teaser list

- components/x-live-blog-post/.npmignore
- components/x-live-blog-wrapper/.npmignore
- components/x-privacy-manager/.npmignore
- components/x-teaser-list/.npmignore
- components/x-teaser/.npmignore
- components/x-topic-search/.npmignore
- private/blueprints/component/.npmignore
Since 8.0, consumers need to pull in the SCSS directly from the `src` directory, rather than a bundled version of the generated CSS in the `dist` directory. Unfortunately, some components (probably the ones generated by the `blueprint.js` script,) have an `.npmignore` file that tells npm not to publish the `src` directory, so these components weren't having their SCSS published. Seeing as most components were fine without an `.npmignore` file let's just delete it from all of the components so that the SCSS can be published. Some other stuff might also be spuriously included in the published bundle but it hasn't been an issue with the other components!
> Publish src folder for all packages

- components/x-gift-article/readme.md
- components/x-gift-article/src/Form.jsx
- components/x-gift-article/src/GiftArticle.jsx
- components/x-gift-article/src/GiftArticle.scss
- components/x-gift-article/src/ReferAFriend.jsx
- components/x-gift-article/src/ReferAFriend.scss
- components/x-gift-article/src/lib/constants.js
- components/x-gift-article/storybook/error-response.js
- components/x-gift-article/storybook/free-article.js
- components/x-gift-article/storybook/native-share.js
- components/x-gift-article/storybook/with-enterprise-first-time-user.js
- components/x-gift-article/storybook/with-enterprise-no-credits.js
- components/x-gift-article/storybook/with-enterprise-request-access.js
- components/x-gift-article/storybook/with-enterprise-sharing-link.js
- components/x-gift-article/storybook/with-enterprise.js
- components/x-gift-article/storybook/with-gift-credits.js
- components/x-gift-article/storybook/with-gift-link.js
- components/x-gift-article/storybook/without-gift-credits.js
This PR adds an additional section to the gift article component.
The section is an optional Refer a Friend feature with a title, description and copyable url.
The intention is to run it as an AB test on `next-article`. 
I've tried keeping the code as isolated as possible, so it can be removed or improved (dynamic urls) later, while also seemingly integrating it with the existing code.
https://financialtimes.atlassian.net/browse/RS-17
https://www.figma.com/file/YUc6OErd2vMIQocCrt8n0t/Refer-a-friend-(RAF)?node-id=37%3A514
> Adds refer a friend feature to gift article

- components/x-gift-article/src/Form.jsx
- components/x-gift-article/src/ReferAFriend.jsx
Removes the usage of `<></>` as it works on storybook by creating React.Fragment but it breaks on other apps that don't use react.
> Fix gift-article not supported fragments

- components/x-gift-article/src/ReferAFriend.jsx
- components/x-gift-article/src/Url.jsx
- components/x-gift-article/src/UrlSection.jsx
fix aria-label on inputs for voice commands so they content entirely the text of the title section where they are contained.
[ticket](https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1316?modal=detail&selectedIssue=CI-1367)
> fix aria-label from inputs

- components/x-gift-article/src/Message.jsx
- components/x-gift-article/src/Title.jsx
This updates the dialog heading "Share this Article" to be an H2 to provide a clearer indication for screen reader users of the structure of the content.
The h4 was changed to an h3 to follow a logical and numerical hierarchical structure.
> CI-1371 - Change div to H2s and H4 to H3s

- components/x-gift-article/src/Buttons.scss
- components/x-gift-article/src/ReferAFriend.jsx
- components/x-gift-article/src/Url.jsx
- components/x-gift-article/src/UrlSection.jsx
After a user activates the share option, and chooses the ‘FT subscribers only’ option in the modal, they are presented with a form field containing the link for the article. However, the form field has not been provided with a visual label to inform users of the purpose of the field.
This also means that voice activation users are unable to discern what voice command is required to access the form field.
Users were not presented instructions or labels to identify the controls in a form and describe what input data is expected. Those with cognitive, language, and learning disabilities may find labels help them to enter information correctly. Labels may also help to prevent users from making submission errors. For voice activation users, visible labels can be used to indicate the accessible …
> [CI-1368] fix accessibility errors

- components/x-live-blog-post/package.json
- components/x-live-blog-post/readme.md
- components/x-live-blog-post/src/LiveBlogPost.jsx
- components/x-live-blog-post/src/__tests__/LiveBlogPost.test.jsx
We want to render live blogs using data retrieved from the new cp-content-pipeline-api. This should work in parallel to the old live blogs, so we can test behind a flag.
I've decided to modify the existing x-live-blog-post component to support either Next ES content or cp-content-pipeline content. There are only two fields affected - the body and the byline. The reason for choosing to modify the existing component is so that we can support both variants behind a flag, and so that we can choose to do a phased rollout with the live-event-api (which is still returning ES content).
This does mean that the live-blog-post component is a little messy, as it is supporting three different types of content 😬 . This isn't really helped by the fact that we're spreading them all as props, making it …
> feat: support cp-content-pipeline liveblog posts

- components/x-follow-button/__tests__/x-follow-button.test.jsx
- components/x-follow-button/src/FollowButton.jsx
[Jira ticket 1](https://financialtimes.atlassian.net/browse/CON-2075)  
[Jira ticket 2](https://financialtimes.atlassian.net/browse/CON-2076)
The label in name criterion requires that the visible label be contained in the accessible name. At the moment they are different: "Added" vs "Remove from myFT".
Use the strings "Add to myFT: conceptName" and  "Added conceptName to myFT: click to remove". Here the visual labels 'Added' and 'Add to myFT' are the first in the aria label.   
The information "click to remove" allows to be aware of the action when clicking the button.  
The visual string is no longer broken. 
Run storybook and inspect the x-follow-button to see the aria-label
> CON-2075, CON-2076: Refactor follow-button aria-label

- readme.md
Non-fork version of this PR: https://github.com/Financial-Times/x-dash/pull/664
As per the title, I have updated the readme so it matches the current [engines](https://github.com/Financial-Times/x-dash/blob/main/package.json#L86-L89) key in package.json. 
This caught me out while setting it up locally. New to the FT so any feedback is most welcome.
> Update readme versions of node and npm to match package engines key

- components/x-gift-article/src/Buttons.jsx
- components/x-gift-article/src/Form.jsx
- components/x-gift-article/src/GiftArticle.jsx
- components/x-gift-article/src/GiftArticle.scss
- components/x-gift-article/src/Message.jsx
- components/x-gift-article/src/Message.scss
- components/x-gift-article/src/RadioButtonsSection.jsx
- components/x-gift-article/src/Url.jsx
- components/x-gift-article/src/UrlSection.jsx
- components/x-gift-article/storybook/free-article-with-enterprise-sharing.js
- components/x-gift-article/storybook/index.jsx
This PR tweaks the behaviour of `x-gift-article` to make a few adjustments concerning Enterprise Sharing. The main difference is that when sharing a free to read article with Enterprise Sharing enabled, users will now see the option to share with Enterprise Sharing alongside the default share option.
This is necessary because articles commonly remain free to read for a short period of time before going behind the paywall and we've had feedback from several Enterprise Sharing clients expressing frustration that the standard links to the article they've shared stop working when this happens. Enterprise Sharing clients can also track how many times their links have been opened and therefore some would prefer to share free to read articles via Enterprise Sharing to have visibility over this. …
> ENTST-139 Add Enterprise Sharing to FTR Articles

- components/x-live-blog-post/package.json
- components/x-live-blog-post/readme.md
- components/x-live-blog-post/src/LiveBlogPost.jsx
- components/x-live-blog-post/src/__tests__/LiveBlogPost.test.jsx
- components/x-live-blog-wrapper/readme.md
- components/x-live-blog-wrapper/src/LiveBlogWrapper.jsx
This should never have worked but sort of does because of some npm workspace magic I don't understand. To prevent us having to import `cp-content-pipeline-ui`, have consumers pass the `RichText` component in as a prop. This also means we don't have to update this component every time `cp-content-pipeline-ui` is updated.
This is a breaking change.
> Prevent circular dependency with cp-content-pipeline-ui

- components/x-live-blog-post/package.json
- components/x-live-blog-post/src/ShareButtons.jsx
- components/x-live-blog-post/src/svgIcons.jsx
- components/x-live-blog-post/storybook/index.jsx
set as peerDependency @financial-times/o-share to 9.0.0 and add code needed to work with this version properly on x-live-blog-post component
[ticket](https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?modal=detail&selectedIssue=CI-1373)
> feat: add new version of o-share to x-live-blog-post

- components/x-increment/src/Increment.jsx
- components/x-interaction/readme.md
- components/x-interaction/src/Hydrate.jsx
- components/x-interaction/src/Interaction.jsx
in #688 i moved x-live-blog-post's `RichText` import to a property to prevent a circular dependency with `cp-content-pipeline-ui`. however, that can't be serialised by `x-interaction`, so when `next-article` hydrates the component it won't render the `RichText` component.
this PR adds support for passing additional properties to every instance of a particular `x-interaction` component to be passed in when hydrating it, allowing consumers of `x-live-blog-wrapper` to pass in `RichText`.
> CPP-1212 support passing additional properties in for hydration

- components/x-gift-article/src/RadioButtonsSection.jsx
This PR fixes a bug whereby B2C users were erroneously seeing the 'Enterprise Sharing' option in the Gift Article radio buttons. This was happening because the specific logic controlling which radio buttons to display was quite confusing.
I've now separated out that logic. There's some minor repetition of code which I think is justified by making the logic clearer and easier to understand. I've also added a few code comment to explain it.
> Bugfix: Gift Article Radio Buttons

- components/x-teaser/Props.d.ts
- components/x-teaser/__fixtures__/video.json
- components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/src/Image.jsx
Originally it was to solve one or two DAC issues ([here](https://financialtimes.atlassian.net/jira/software/c/projects/CON/boards/1061?modal=detail&selectedIssue=CON-2078) and [there](https://financialtimes.atlassian.net/jira/software/c/projects/CON/boards/1061?modal=detail&selectedIssue=CON-2077) where the people using tabs and screen reader did not have enough info about what was about to happen when they clicked on the video. We needed to let them know what video it was, and to use the text that was on the image of the video. Well. Except that another PR removed the ability to tab through the videos for another reason. But for consistency purposes with this [PR](https://github.com/Financial-Times/next-home-page/pull/1200), we are still adding the alt text to those images on top of …
> CON-2077, CON-2078: Adds alt text to image of video teaser

- components/x-gift-article/__tests__/x-gift-article.test.jsx
Jira ticket ---> https://financialtimes.atlassian.net/browse/ACC-2349
This PR adds basic unit tests to the `x-gift-article` component, as it was spotted that no tests currently exist. This is not a 100% full coverage (as its quite difficult to test everything with the component). However, this covers the key features of:
- Displays the correct data given its initial props
- Displays the correct html when using the "show" functions
- Calls the correct APIs
- Displays the responses from the API calls
- Responds to 0 credit scenarios
To run tests, please run `npm run test` 
You can run, just these unit tests for x-gift-artcle with `jest ./components/x-gift-article/__tests__/* --verbose`
> ACC-2349 test(x-gift-article): adds basic unit tests

- components/x-gift-article/package.json
- components/x-gift-article/src/Buttons.jsx
- components/x-gift-article/src/Form.jsx
- components/x-gift-article/src/GiftArticle.jsx
- components/x-gift-article/src/GiftArticle.scss
- components/x-gift-article/src/HighlightCheckbox.jsx
- components/x-gift-article/src/HighlightRecipientMessage.jsx
- components/x-gift-article/src/HighlightRecipientMessage.scss
- components/x-gift-article/src/HighlightSavedMessage.jsx
- components/x-gift-article/src/HighlightSavedMessage.scss
- components/x-gift-article/src/HighlightSection.jsx
- components/x-gift-article/src/HighlightSection.scss
- components/x-gift-article/src/Message.jsx
- components/x-gift-article/src/UrlSection.jsx
- components/x-gift-article/src/lib/enterpriseApi.js
- components/x-gift-article/src/lib/highlightsApi.js
- components/x-gift-article/storybook/with-enterprise.js
This PR introduces two features
- Highlights checkbox that creates a share with highlights included
- A new message is introduced to B2B recipients in the x-gift-article prompting the users to save their highlights in order to re-share the article with the received highlights.
Changes:
- Updated the entrepriseApi
- Created a separate highlightsApi client to be used only for requests to the user-annotations-api
- Created HighlightsSection component to be a wrapper of the highlights checkbox, the recipient message for saving highlights and the success message afterwards.
- Created a HighlightCheckbox component, which will appear after the user has saved the shared highlights or when the user has created highlights on their own.
- Created a new message HighlightRecipientMessage which will be …
> X-Gift article highlights sharing Release

- components/x-gift-article/src/GiftArticle.jsx
The highlights checkbox is visible even when the article has no highlights. Switched to get the `highlightsClassName` property from the `state` instead of `initialProps`.
> Get highlightsClassName from state

- components/x-gift-article/src/HighlightSection.jsx
changes to x-gift-article component 
- remove the page reload when saving highlights 
- dispatch events when saving highlights 
[ticket](https://financialtimes.atlassian.net/browse/ENTST-513)
> remove page reload when saving highlights

- components/x-live-blog-post/src/__tests__/LiveBlogPost.test.jsx
- components/x-live-blog-wrapper/src/LiveBlogWrapper.jsx
Summary: Adds a `backToTop` prop to x-live-blog-wrapper
`backToTop` is currently an x-live-blog-post level argument but we don't really have a use case for this being post-level rather than live-blog level. I'm adding it in now so that I can use it in the new Content Pipeline UI that currently being developed - [relevant PR](https://github.com/Financial-Times/cp-content-pipeline/pull/383)
The prop can be either a string or a function to support the different implementations currently in place for dotcom and the App
Change is additive and non-breaking 🤞
> Make backToTop a Wrapper level prop for live blogs

- components/x-gift-article/__tests__/x-gift-article.test.jsx
- components/x-gift-article/package.json
- components/x-gift-article/src/CopyConfirmation.jsx
- components/x-gift-article/src/GiftArticle.jsx
- components/x-gift-article/src/lib/tracking.js
- components/x-gift-article/src/v2/Footer.jsx
- components/x-gift-article/src/v2/FooterMessage.jsx
- components/x-gift-article/src/v2/GiftLinkSection.jsx
- components/x-gift-article/src/v2/Header.jsx
- components/x-gift-article/src/v2/ShareArticleDialog.jsx
- components/x-gift-article/src/v2/ShareArticleDialog.scss
- components/x-gift-article/src/v2/SharedLinkTypeSelector.jsx
- components/x-gift-article/storybook/index.jsx
- components/x-gift-article/storybook/share-article-dialog-b2c.jsx
- components/x-gift-article/storybook/share-article-dialog.js
- package-lock.json
- set the Project to `Automated kanban with reviews`, but remove the `To Do` column
- If you're not …
> ENTST-455: User journey flow update - B2B non advanced-sharing / B2C

- components/x-gift-article/__tests__/x-gift-article.test.jsx
- components/x-gift-article/package.json
- components/x-gift-article/src/GiftArticle.jsx
- components/x-gift-article/src/main.scss
- components/x-gift-article/src/v2/GiftLinkSection.jsx
- components/x-gift-article/src/v2/ShareArticleDialog.scss
- components/x-gift-article/src/v2/SocialShareButtons.jsx
- components/x-gift-article/src/v2/UrlSection.jsx
- components/x-gift-article/storybook/index.jsx
- components/x-gift-article/storybook/share-article-modal-b2c.jsx
- components/x-gift-article/storybook/share-article-modal-with-advanced-sharing.jsx
- components/x-gift-article/storybook/share-article-modal.js
- jest.config.js
https://github.com/Financial-Times/x-dash/assets/10318770/1fc45534-a356-4abb-b30a-6b73e700fc0b
- set …
> ENTST-448: update social share buttons

- components/x-gift-article/__tests__/x-gift-article.test.jsx
- components/x-gift-article/package.json
- components/x-gift-article/readme.md
- components/x-gift-article/src/Form.jsx
- components/x-gift-article/src/GiftArticle.jsx
- components/x-gift-article/src/v2/AdvancedSharingOptions.jsx
- components/x-gift-article/src/v2/NoCreditAlert.jsx
- components/x-gift-article/src/v2/ReceivedHighlightsAlert.jsx
- components/x-gift-article/src/v2/ShareArticleDialog.jsx
- components/x-gift-article/src/v2/ShareArticleDialog.scss
- components/x-gift-article/src/v2/SharedLinkTypeSelector.jsx
- components/x-gift-article/src/v2/SocialShareButtons.jsx
- components/x-gift-article/src/v2/UrlSection.jsx
- components/x-gift-article/storybook/index.jsx
- components/x-gift-article/storybook/share-article-modal-b2c-no-credits.jsx
- components/x-gift-article/storybook/share-article-modal-b2c.jsx
- components/x-gift-article/storybook/share-article-modal-no-credits.jsx
- components/x-gift-article/storybook/share-article-modal-with-advanced-sharing-no-gift-credits.jsx
- components/x-gift-article/storybook/share-article-modal-with-advanced-sharing-save-highlights-message.jsx
- components/x-gift-article/storybook/share-article-modal-with-advanced-sharing.jsx
- components/x-gift-article/storybook/share-article-modal.js
- components/x-gift-article/storybook/with-enterprise-first-time-user.js
- components/x-gift-article/storybook/with-enterprise-no-credits.js
- components/x-gift-article/storybook/with-enterprise-request-access.js
- components/x-gift-article/storybook/with-enterprise-sharing-link.js
- components/x-gift-article/storybook/with-enterprise.js
- components/x-gift-article/storybook/with-gift-credits.js
- components/x-gift-article/storybook/with-gift-link.js
https://github.com/Financial-Times/x-dash/assets/10318770/d5c8dc20-a454-4236-bfe4-41812351c01d 
- …
> ENTST-451: update share messaging when highlights are received

- components/x-gift-article/__tests__/x-gift-article.test.jsx
- components/x-gift-article/src/GiftArticle.jsx
- components/x-gift-article/src/v2/CreateLinkButton.jsx
- components/x-gift-article/src/v2/FooterMessage.jsx
- components/x-gift-article/src/v2/FreeArticleAlert.jsx
- components/x-gift-article/src/v2/GiftLinkSection.jsx
- components/x-gift-article/src/v2/Header.jsx
- components/x-gift-article/src/v2/ShareArticleDialog.scss
- components/x-gift-article/src/v2/SharedLinkTypeSelector.jsx
- components/x-gift-article/storybook/index.jsx
- components/x-gift-article/storybook/share-article-modal-b2b-free-article.js
- components/x-gift-article/storybook/share-article-modal-b2c-free-article.jsx
- components/x-gift-article/storybook/share-article-modal-with-advanced-sharing-free-article.jsx
| B2B  | B2C  | AS |
|------------------|------------------|----------------------|
|![Screenshot 2023-07-06 at 13 12 33](https://github.com/Financial-Times/x-dash/assets/10318770/da17a90b-592a-4363-9d27-7e55bff38653)|![Screenshot 2023-07-06 at 13 12 36](https://github.com/Financial-Times/x-dash/assets/10318770/ecde8002-19af-4b9e-8350-f8c59f2aa566)|![Screenshot 2023-07-06 at 13 12 54](https://github.com/Financial-Times/x-dash/assets/10318770/049e1341-7bc1-4813-9a4d-35015d79fe97)|
|![Screenshot 2023-07-06 at 13 12 41](https://github.com/Financial-Times/x-dash/assets/10318770/f5cac21c-4326-4b22-ad53-7a93ef8daf2c)|![Screenshot 2023-07-06 at 13 12 44](https://github.com/Financial-Times/x-dash/assets/10318770/5c8e789e-1c47-40dd-896f-b8a384652cd2)|![Screenshot 2023-07-06 at 13 12 …
> ENTST-538: update copy for free article

- components/x-gift-article/__tests__/x-gift-article.test.jsx
- components/x-gift-article/src/v2/AdvancedSharingOptions.jsx
- components/x-gift-article/storybook/share-article-modal-with-advanced-sharing-free-article.jsx
- components/x-gift-article/storybook/share-article-modal-with-advanced-sharing-no-enterprise-credits.jsx
- components/x-gift-article/storybook/share-article-modal-with-advanced-sharing-no-gift-credits.jsx
- components/x-gift-article/storybook/share-article-modal-with-advanced-sharing-save-highlights-message.jsx
- components/x-gift-article/storybook/share-article-modal-with-advanced-sharing.jsx
Fix to issue found in testing which enabled users to select 'share highlights' even when there are no highlights on the article
https://github.com/Financial-Times/x-dash/assets/10318770/013e1534-3770-4e77-a80e-38b816ca4831
ENTST-547
- If you're using this workflow, create a Label and a Project for your component and ensure all small PRs are attached to them. Add the Project to the …
> fix: highlights checkbox displaying when highlights are not selected

- components/x-gift-article/src/UrlSection.jsx
| before | after|
| --- | --- |
| ![Screenshot 2023-07-11 at 10 52 29](https://github.com/Financial-Times/x-dash/assets/10318770/13a2683e-989b-4feb-8e2c-0a3ec47f69b3) | ![Screenshot 2023-07-11 at 10 52 36](https://github.com/Financial-Times/x-dash/assets/10318770/c29df766-7cf1-4c92-aaf6-43ca4da23f3d) |
- If you're using this workflow, create a Label and a Project for your component …
> ENTST-557: fix "Copy link" cta text casing

- components/x-gift-article/src/SharedLinkTypeSelector.jsx
The alert text for when a user runs out of sharing credits has been updated as shown below
| before | after |
|---|---|
| ![Screenshot 2023-07-10 at 11 49 43](https://github.com/Financial-Times/x-dash/assets/10318770/a9ad7207-ad52-4196-bec3-44a3623bf346) | ![Screenshot 2023-07-10 at 11 47 56](https://github.com/Financial-Times/x-dash/assets/10318770/e62e40fe-fc1f-4da4-b150-b4d7bad2c0f1) |
| ![Screenshot 2023-07-10 at 11 49 45](https://github.com/Financial-Times/x-dash/assets/10318770/7df0a141-fda8-42d5-b51a-3439d91f1456) | ![Screenshot 2023-07-10 at 11 48 00](https://github.com/Financial-Times/x-dash/assets/10318770/be95bbb7-9899-4287-b5ed-806626a53f03) |
If this is your first `x-dash` pull request please familiarise yourself with the [contribution …
> ENTST-552: update no credits copy

- components/x-gift-article/src/ShareArticleDialog.scss
This PR addresses the mail icon hover state issue affecting B2B users on `next-article`, see screenshots below for illustration.
| before | after |
| ---| --- |
| ![Screenshot 2023-07-10 at 16 24 37](https://github.com/Financial-Times/next-article/assets/10318770/ff0ec022-c598-4c92-bd00-c6cb5787d9f1) | ![Screenshot 2023-07-10 at 16 25 03](https://github.com/Financial-Times/next-article/assets/10318770/f00eaf82-7a21-45b0-9f9c-69ec063cddc8) |
- If this will be a long-lived PR, consider using smaller PRs targeting this branch for individual features, so …
> ENTST-553: mail icon hover state

- components/x-gift-article/src/CreateLinkButton.jsx
- components/x-gift-article/src/ShareArticleDialog.jsx
- components/x-gift-article/src/SocialShareButtons.jsx
- components/x-gift-article/src/UrlSection.jsx
Added new data-tracking values in gift article to improve the statistics diagrams in Amplitude.
- Moved the tracking for the link type from copy to create link
- Added new tracking for copying link
- Added `share-modal` value to distinguish from where the social share was made
- Added `b2b` and `b2c` to identify the user
All available tracking journeys for the gift article: 
- Share -> Create link
- data_trackable_path = “share | top | share-modal | b2b | nonGiftLink"
- Share -> Give access to non-subscribers -> Multiple people
- data_trackable_path = share | top | share-modal | b2b | enterpriseLink"
- Share -> Give access to non-subscribers -> One person
- data_trackable_path = “share | top | share-modal | b2b | giftLink"
- Share -> Create link(does not matter which type of link) -> Copy …
> Gift Article Tracking changes

- components/x-gift-article/src/GiftArticle.jsx
- components/x-gift-article/src/SocialShareButtons.jsx
- Previous behavior
- When a user clicks a social share icon the link associated with the icon is a standard link(even for Advanced Sharing). 
- Current behavior 
- When a user clicks a social share icon the link associated with the icon will be the same as what the user has chosen to generate. 
https://financialtimes.atlassian.net/browse/ENTST-591
Now the share link that appears in Twitter's modal is the same as the link generated in the `x-gift-article` modal. 
https://github.com/Financial-Times/x-dash/assets/22678655/f809d226-c12d-410a-8077-9b391d1e774d
> Social Share Url Fix in x-gift-article

- components/x-gift-article/src/FooterMessage.jsx
Following Arman's comments on the [Advanced Sharing Highlights tracking spec](https://docs.google.com/spreadsheets/d/1_0Oe5nG-zF_zgFAWFipkXazch_gG8_eQ_0Hsk7IngSY/edit#gid=473047355), I'm adding data-trackables to the footer message
> add data-trackables to footer message on gift-article

- components/x-gift-article/src/ShareArticleDialog.jsx
- components/x-gift-article/src/ShareArticleDialog.scss
- Since we don't use `o-overlay` for the sharing modal, we had to get rid of the `o-overlay__close` style for the close button. 
- Created a custom style class and copied the style of the close button from `o-overlay` so the style of the button does not break in the future when the o-overlay gets updated. 
- The modal is closed with an event in `next-article`
- Link to the PR in `next-article` https://github.com/Financial-Times/next-article/pull/5281
https://financialtimes.atlassian.net/browse/ENTST-644
> Modify close button

- components/x-live-blog-post/src/ShareButtons.jsx
- components/x-live-blog-post/src/__tests__/ShareButtons.test.jsx
Patch
When sharing a live blog post to Twitter/X, the Tweet gets appended with 'via @financialtimes'. We want to change this to 'via @ft'.
✅ Old content pipeline
✅ New content pipeline
❌ App (the app doesn't use share buttons on live blog posts)
> Update Twitter handle when sharing live blog posts

- components/x-gift-article/__tests__/x-gift-article.test.jsx
- components/x-gift-article/src/AdvancedSharingBanner.jsx
- components/x-gift-article/src/FooterMessage.jsx
- components/x-gift-article/src/Header.jsx
- components/x-gift-article/src/ShareArticleDialog.jsx
- components/x-gift-article/src/ShareArticleDialog.scss
- components/x-gift-article/src/SharedLinkTypeSelector.jsx
- components/x-gift-article/src/SocialShareButtons.jsx
This PR includes multiple bug fixes in `x-gift-article`:
- Updated the Advance Sharing marketing link
- Replaced `main` tag with `div` because only one `main` tag should be present in the page. 
- Updated the close button of the modal.
- Since we don't use `o-overlay` for the sharing modal, we had to get rid of the `o-overlay__close` style for the close button.
- Created a custom style class and copied the style of the close button from `o-overlay` so the style of the button does not break in the future when the `o-overlay` gets updated.
- Updated the headings hierarchy and their styles to match the previous design. That change helps screen readers to navigate easily through the modal. 
- Changes to the copy in modal so that we distinguish between plural and singular for users depending …
> x-gift-article release branch

- components/x-privacy-manager/src/__tests__/helpers.js
- components/x-privacy-manager/src/actions.js
In preparation for the rollout of the new Sourcepoint based Consent Management System (CMP) there is a small update required to ensure that the CCPA consent toggle choices are respected in the ads-stack.
Specifically, when the new CMP is live, the ad-stack will check for the `permutiveAds` value in the FTCONSENT cookie / SCS when determining wether or not to run Permutive code.
This small PR ensures that the CCPA block/allow toggles will set the new 'permutiveAds' category value in the SCS and FTCONSENT cookie.
> Privacy Manager - Setting permutiveAds as a consent category value

- components/x-gift-article/readme.md
- components/x-gift-article/src/AdvancedSharingOptions.jsx
- components/x-gift-article/src/GiftArticle.jsx
- components/x-gift-article/src/ShareArticleDialog.scss
- components/x-gift-article/src/SharedLinkTypeSelector.jsx
- components/x-gift-article/src/lib/api.js
- components/x-gift-article/src/lib/constants.js
- components/x-gift-article/src/lib/highlightsApi.js
- components/x-gift-article/src/lib/variables.scss
- components/x-gift-article/src/main.scss
This PR updates the behaviour of x-gift-article component to add the option to include highlights when using gift  & non-gift sharing for B2B users. The new logic is as follows:
- Option to 'include highlights' has been added to the share modal for gift article and non-gift share
- If a B2B user selects 'include highlights', a highlight share token is generated via the Professional user-annotations-api
- The highlights token is appended as a query param to the share url, along with the article share token, and is then shortened by bit.ly before being returned to the user
this PR only changes code in the x-gift-article component
| Before | After |
| -------- | -------- |
| B2B users who have highlights in their articles can see the include highlights check box only when they use the …
> include highlights to non-gift & gift shares

- components/x-gift-article/src/AdvancedSharingOptions.jsx
- Ensures that the `Include highlights` checkbox remains ticked when switching between one and multiple people.
https://github.com/Financial-Times/x-dash/assets/1771189/2e3bee3a-1236-42cc-95fa-74a383b7d253
https://github.com/Financial-Times/x-dash/assets/1771189/160422f7-5380-4e7e-804e-b919770dc954.mov
> ENTST 807 | Keep include highlights box ticked when switching between options

- components/x-gift-article/src/GiftArticle.jsx
A New Advanced Sharing tooltip will be displayed on `next-article` after the first use of AS.  
Every time a user creates a new  Adanvced Sharing link the `ES_COUNT` cookie gets updated with the total number of shares.
Changes: 
- A new custom event will be dispatched based on the `ES_COUNT` value after the user creates a new Advanced Sharing link. 
-  If `ES_COUNT` is equal to 1 an `advanced-sharing-first-use` event will be dispatched and later on caught by `next-article`.
https://financialtimes.atlassian.net/browse/ENTST-790
> Add Advance Sharing first use event dispatch

- components/x-article-save-button/src/ArticleSaveButton.jsx
PR to add a property to `x-article-save-button` to make it icon only 
| Before  | After |
| ------------- | ------------- |
|![Screenshot from 2024-02-07 18-16-20](https://github.com/Financial-Times/x-dash/assets/110396496/3af370b3-7c8c-4acf-a1a1-00effaec41ae)|![Screenshot from 2024-02-07 19-21-02](https://github.com/Financial-Times/x-dash/assets/110396496/240e3943-f742-4832-b118-f322e990e900)|
> add optional prop to make article save button icon only

- packages/x-engine/src/webpack.js
If we use x-engine inside a package in a monorepo usually the react / engine  dependencies should be resolved to the parent node_modules . Currently x-engine set an alias resolving only from the the node_modules within the main package so in case you use it in a package inside a monorepo it wont work. With this fix we don't override a resolver alias already set and therefore we allow in a monorepo to set where we want to resolve these packages and make it work. 
For example in a monorepo package that use webpack we could set something like this and make it work
```
resolve: {
alias: {
"react": '../../node_modules/react',
"react-dom": '../../node_modules/react-dom',
},
},
```
**Why this change ?** 
Currently in cp-content-pipeline monorepo we use storybook inside the ui package and we need …
> fix: do not override current resolvers

- components/x-gift-article/__tests__/x-gift-article.test.jsx
- components/x-gift-article/src/GiftArticle.jsx
- Don't show the highlights recipient message if the article content has changed since the shared article highlights were first added
- Adds a test to ensure that the save the highlights message is not displayed when the article content has changed since highlights were added
- Locally using an instance of `next-article` with the `x-gift-article` package linked.
> ENTST 788 | Remove save message for highlighted article with different content

- packages/x-engine/package.json
Allow to install x-engine along with webpack 5 or greater.
I have tested with it and works right. Also i think probably is going to work with future versions too thats why set greater than version 4.
> fix: give webpack >=4 support to x-engine

- components/x-gift-article/src/CreateLinkButton.jsx
- components/x-gift-article/src/RegisteredUserAlert.jsx
- components/x-gift-article/src/ShareArticleDialog.scss
- components/x-gift-article/src/SharedLinkTypeSelector.jsx
- components/x-gift-article/src/SharingOptionsToggler.jsx
A small PR to adjust padding of share-modal and fix off looking Non-subscriber
More in [ELES-1147](https://financialtimes.atlassian.net/browse/ELES-1147)
and fix registered-user case as in [ELES-1066](https://financialtimes.atlassian.net/browse/ELES-1066)
[ELES-1147]: https://financialtimes.atlassian.net/browse/ELES-1147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ELES-1066]: https://financialtimes.atlassian.net/browse/ELES-1066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adjust top padding for share modal & fix off looking Non-subscriber

- components/x-gift-article/src/SharingOptionsToggler.jsx
Fix small issue related with Include highlight checkbox on Advanced sharing. After switching to second tab on the Advanced sharing modal, the "Include Sharing" checkbox was always unchecked, instead pf preserving its current state from the previous tab
https://financialtimes.atlassian.net/browse/ELES-1161
Checkout the branch, install the dependencies and run the story book. From the storybook check behavior of the Share article modal (B2b with highlights) - http://local.ft.com:9001/?path=/story/x-gift-article--share-article-modal-b-2-b-highlights 
- Discuss features first
- Update the documentation
- **Must** be tested in FT.com and Apps before merge
- No hacks, experiments or temporary workarounds
- Reviewers are empowered to say no
- Reference other issues
- Update affected stories and …
> ELES-1161 Preserve Include Highlights checkbox state through tabs

- components/x-teaser-timeline/__tests__/__snapshots__/TeaserTimeline.test.jsx.snap
- components/x-teaser/__tests__/__snapshots__/snapshots.test.js.snap
- components/x-teaser/src/Image.jsx
This PR changes way to solve CLS in x-teaser being more reliable in more scenarios. The previous approach was creating padding that in some scenarios wasn't needed sometimes.
This code is already in [o-teaser ](https://github.com/Financial-Times/origami/blob/a11c67c58b4909a7aad294dd36e4636621c1d360/components/o-teaser/src/tsx/image.tsx#L8)
[ticket](https://financialtimes.atlassian.net/jira/software/c/projects/CI/boards/1653?selectedIssue=CI-2167)
> fix: change way to solve CLS in teaser images

- components/x-teaser/Props.d.ts
- components/x-teaser/readme.md
- components/x-teaser/src/PromotionaContent.jsx
- components/x-teaser/src/Teaser.jsx
- components/x-teaser/src/concerns/rules.js
If this is your first `x-dash` pull request please familiarise yourself with the [contribution guide](https://github.com/Financial-Times/x-dash/blob/HEAD/contribution.md) before submitting. ✔️ 
- This PR is the first piece of the puzzle for integrating Clips on the ft-app homepage. If you'd like you can familiarise yourself with the [spike](https://financialtimes.atlassian.net/wiki/spaces/CON/pages/8334606380/Clips+on+Homepage+-+App). We are going to inject Promotional Content through a property. Promotional content in the case of clips will be `cp-content-pipeline` Clip component. To not over-complicate things and not create unnecessary dependencies between `cp-content-pipeline` and `x-dash` we've decided to take the approach of injection. 
- The approach was previously discussed and …
> [CON-3298] Inject promotional content inside Teaser

- components/x-teaser/src/PromotionaContent.jsx
This change applies the existing logic added to the image container on the ft-app. We can avoiding duplication of this logic for the promotional content wrapper in the ft-app and wouldn't need to replicate it for the new class name.
Downside of this method is the situation where promotional content has a class name of `o-teaser__image-container`, _but_ it is way safer than trying to rename this class and image container class to something like `o-teaser__media-container`. 
We do have the same logic for the next-home-page where we reused the existing image class name for the teaser image and the clip component.
> feat: rename promo content wrapper to match image container

- components/x-follow-button/package.json
- package-lock.json
Description:
As part of this PR we need to update the instant alert component icon: https://financialtimes.atlassian.net/browse/CON-3316
n-myft-ui is dependency of next-myft-page as well of  "x-follow-button" as npm is not able to resolve different versions in next-myft-page of “n-myft-ui”, it is necessary to update this dependency in both projects hence the reason for this PR
Breaking changes:
[v34.0.0](https://github.com/Financial-Times/n-myft-ui/releases/tag/v34.0.0)
What's Changed
This version are mainly for these changes and it is a breaking release because it removes the browser alert preference.
[v33.0.0](https://github.com/Financial-Times/n-myft-ui/releases/tag/v33.0.0)
What's Changed
UG-1414: Remove notification for users referred from podcast links by @jamesnicholls in …
> CON-3316: bump n-myft-ui dependency

- components/x-gift-article/src/SharingOptionsToggler.jsx
- components/x-gift-article/src/lib/highlightsApi.js
This PR fixes a couple of issues related to the 'share with highlights' feature.
Currently, whenever a user selects "FT subscribers only", even if the article contains no highlights for the user, we still request a highlights access token.
Whenever the user selected "FT subscribers only", we `setIncludeHighlights` to the value of _the "Anyone/FT subscribers only"_ switcher, which evaluates to true. This is an issue particularly when the article contains no highlights, as we don't display the 'Include Highlights' checkbox, but we're still setting it to true.
This PR makes sure that we're only setting `includeHighlights` when the user wishes to.
If also adds some error handling to the code that requests the highlights token. Currently this endpoint does not return an error, but it soon will …
> Fix automatic 'setIncludeHighlights' + handle errors from highlights token request (ELES-1237)

- components/x-gift-article/src/SocialShareButtons.jsx
[ELES-1100](https://financialtimes.atlassian.net/browse/ELES-1100)
Currently the share via whatsapp only works when the users have the app installed on their machine, 
In this PR we changed the whatsapp url to the universal format to fallback to whatsapp web if the app is not installed
[ELES-1100]: https://financialtimes.atlassian.net/browse/ELES-1100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ELES-1100  Fix whatsapp linking

- CODEOWNERS
- components/x-gift-article/src/GiftArticle.jsx
PR #782 has introduced a small bug since the initial value for `includeHiglights` prop is now true it caused a bug when sharing an article that doesn't have highlights this PR is a fix for it
> Fix includeHighlights initial value

- components/x-gift-article/__tests__/x-gift-article.test.jsx
- components/x-gift-article/readme.md
- components/x-gift-article/src/ShareArticleDialog.scss
- components/x-gift-article/src/UrlSection.jsx
- components/x-gift-article/src/lib/share-link-actions.js
This PR adds the functionality to include the highlights when copying the link for sharing the article. 
If the user chooses to not include the highlights in the shared link, we only copy the shortened link for the article.
On the other hand, if the user chooses to include the highlights, the shared text is the highlight (trimmed to 30 words) and the  shortened link.
> ELES-1362 share highlight preview when copying a link

- components/x-gift-article/src/AdvancedSharingOptions.jsx
- components/x-gift-article/src/SharedLinkTypeSelector.jsx
The B2C customers with Standard subscription says it misleading to say they can gift up to 20 articles while only having 10 credits for Standard. The monthly allowance count of gift article (20 articles) was hardcoded in the `AdvancedSharingOptions` and `SharedLinkTypeSelector` components. But actually, we have already had information about the monthly allowance of gift articles for the given user. So, this actual count of gift article is used and issue is fixed with this PR. 
**Link to the reported issue in Slack** -> https://financialtimes.slack.com/archives/C03AKKF5A5R/p1736205606862409
| Before | After |
| ---- | ---- |
| <img width="1384" alt="Screenshot 2025-01-07 at 17 36 26" src="https://github.com/user-attachments/assets/b9e3afae-51e0-4959-9ab0-32b7d6a27ed9" /> | <img …
> ELES-1532 Advanced Sharing Gift Articles - wrong monthly allowance count for B2C customers with standard subscription

- components/x-gift-article/__tests__/x-gift-article.test.jsx
- components/x-gift-article/readme.md
- components/x-gift-article/src/AdvancedSharingOptions.jsx
- components/x-gift-article/src/Header.jsx
- components/x-gift-article/src/ShareArticleDialog.jsx
- components/x-gift-article/src/ShareArticleDialog.scss
- components/x-gift-article/src/SharedLinkTypeSelector.jsx
- components/x-gift-article/storybook/index.jsx
- components/x-gift-article/storybook/share-article-modal-mpr-version.js
- components/x-gift-article/storybook/share-article-modal-no-credits-mpr-version.jsx
- components/x-gift-article/storybook/share-article-modal-with-advanced-sharing-mpr-version.jsx
- components/x-gift-article/storybook/share-article-modal-with-advanced-sharing-no-enterprise-credits-mpr.jsx
The sharing functionality is now available for MPR articles, requiring some x-gift-article features to be hidden. 
-  A new prop `isMPRArticle` is passed to the modal when initialized in `next-article`  to indicate whether the article is MPR, based on its `editorialDesk` value
-  Sharing options toggler(`SharingOptionsToggler`) is hidden for MPR articles. Due to this change the title of `AdvancedSharingOptions` is hidden to match the design.  
- The copy in the header is changed to `Share this article using:` for users with Advanced Sharing access and `Share this article` for B2B users.
- Zero credits copy is also changed
- Added some styles to adjust the margins since the toggler is missing and the style of the modal looks disproportionate
- Adjusted the margin of the textarea after …
> ENTST-1194 | Sharing Monetary Policy Radar(MPR) articles

- components/x-follow-button/package.json
- package-lock.json
Customer Products has ended its partnership with Sentry. As part of this transition, we are removing the @financial-times/o-errors package from ft-app.
Currently, @financial-times/n-myft-ui@^35.0.0 needs to be upgraded to v37 to support this change.
Changes
- Upgraded @financial-times/n-myft-ui from ^35.0.0 to ^37.0.0.
- The major changes between v35 and v37 include:
- Node 20 support, I can see recently this repo has been updated to support Node 20 as well
So, the upgrade of `n-myft-ui` should be a seamless transition without causing much of an issue.
I have tested this by running the storybook as documented in the readme of `x-dash`. Please let me know if I have missed anything.
> [AT-6904] Update n-myft-ui to support v37 which removes o-errors

- CODEOWNERS
if a path in `CODEOWNERS` is more specific, it overrides previous entries that match, and defines the owner for those files as _only_ that team. this means if a PR touches a file in a component, it requires approval from that team, Platforms approval isn't enough.
> chore: allow platforms to approve PRs that touch components

- components/x-gift-article/package.json
- components/x-topic-search/package.json
- components/x-topic-search/src/TopicSearch.scss
- package-lock.json
This is a supplementary PR to the original CP O3 Migration PR which can be found [here](https://github.com/Financial-Times/x-dash/pull/818). 
This PR bumps the versions of `o-labels`, and `o-banner` in `x-gift-article` and removes the use of `o-editorial-typography` from `x-topic-search`, that were missed in the original PR.
> Cp o3 migration extra

- components/x-privacy-manager/src/components/radio-btn.jsx
Fixed radio button component in privacy manager  by reverting the class that was removed during o3 migration for it to respond to user interaction.
This was spotted during the work of https://financialtimes.atlassian.net/browse/CPO3-39
> fix: Fix x-privacy-manager to respond to interaction
